### ISSUE TITLE
Beta branch - Master logging file contain another serie's log

### ISSUE THREAD

**Issue by ZeroQI** [ZeroQI/Hama.bundle#137]
@sven-7 "Within the Bleach log, I began seeing logs for a different show, Blood Blockade Battlefront."
I looked through several others and sees all of the series are getting mixed up with one another."

[Bleach.zip](https://github.com/ZeroQI/Hama.bundle/files/1253505/Bleach.zip)

**Comment by ZeroQI** [comment]
Solutions:
- software locks in major part of the agent from log redirection to last log written
- single thread instead of the double plex seem to use by default (simpler)
- cache all logs to write all at once

From the framework.bundle:
The @parallelize and @task decorators are designed to be used in conjunction with each other -
@parallelize decorates a function that defines one or more @task functions. A ThreadKit-specific
lock is maintained so only one parallelizer can be created at any time. When the parallelizer
has run, the tasks are queued for dispatch to the runtime's task pool, and the calling thread is
blocked until all tasks have completed.

TVDB Source: https://github.com/plexinc-agents/TheTVDB.bundle/blob/master/Contents/Code/__init__.py

**Comment by EndOfLine369** [comment]
I'll take some time to look at this.

* software locks in major part of the agent from log redirection to last log written (Thread.Block?)
** Can you please expand on what your mean here?
* single thread instead of the double plex seem to use by default
** This is bad to performance as people like me that have 600+ series it will take exceedingly long for full refreshes. If my memory serves me right, i've seen my agent logs do 2-3 parallel threads.
* cache all logs to write all at once
** This could be possibly detrimental to memory and thus performance. It might be fine for log sized of series that have ~12 episodes but Bleach/OnePiece/Naruto/NarutoShippuden/... series could cause OOM or other issues from trying to keep all that text in memory.

Note that AAS logging also needs some updates i've been thinking on. The log names/location are problematic when you take into account if the scanner is used on more than one library OR if there is more than one root in a library. Both of these are true in my case.

**Comment by EndOfLine369** [comment]
Re: ASS logging, check my latest commit. https://github.com/ZeroQI/Absolute-Series-Scanner/commit/e34b48de6e049460302b3502e50abd457e51ec64#diff-edf9a02ffa5a0496c5247e048b83f667
Creates a folder under "_Logs" from the last two folder names from the root path (or one if only one exists). EX: root "\\\\NAS\Anime2\t4" creates "Anime2-t4"
![image](https://user-images.githubusercontent.com/16750699/29747820-ec8bd770-8acb-11e7-9d4e-90f162c46eb6.png)

**Comment by ZeroQI** [comment]
I use the folder scan to reset the files. If doing that the scanner need to reset the logs on the root folder scan otherwise resetting will delete needed logs. Also it will group scanning for multiple series together at the top of the logs then the agent logs in logs. I can live with that and logs looks more like the root folder structure.

I don't like using only the last 2 folders to create a folder.
What happens when you share f:\ or multiple drives use same naming convention like video/anime  ? Use the library name instead but might need to put the plex token in an id file and then your solution as backup...

Still need to solve the multiple threads logging in wring file... what if i don't redirect normal logging but use separate logging that can work concurently in multiple threads ? No need for thread functions at all then! That should solve it...

**Comment by EndOfLine369** [comment]
>I use the folder scan to reset the files. If doing that the scanner need to reset the logs on the root folder scan otherwise resetting will delete needed logs. Also it will group scanning for multiple series together at the top of the logs then the agent logs in logs. I can live with that and logs looks more like the root folder structure.

Resetting the individual log files is a simple update to https://github.com/ZeroQI/Absolute-Series-Scanner/blob/Beta/Scanners/Series/Absolute%20Series%20Scanner.py#L296
change the mode from 'a' to 'w'

>I don't like using only the last 2 folders to create a folder.
What happens when you share f:\ or multiple drives use same naming convention like video/anime ? Use the library name instead but might need to put the plex token in an id file and then your solution as backup...

Unfortunately the scanner only knows the filesystem files passed to it as Scan arguments. So that is all that can be used to separate out the scans. Most people will not place the plex token either in my opinion (i don't). We could use the full root at the log foldername, we can do that (EX: root "\\NAS\Anime2\t4" creates "NAS-Anime2-t4"). People should not be using the same root directories for separates Libraries as that is just duplicating the files into Plex. 

>Still need to solve the multiple threads logging in wring file... what if i don't redirect normal logging but use separate logging that can work concurently in multiple threads ? No need for thread functions at all then! That should solve it...

Haven't looked into this yet. Probably have some time this week as will take some time to first read then understand the code setup in the beta agent. I know ASS so I can update it faster as I pretty much have written/corrected half or more of it by now. [See above](https://github.com/ZeroQI/Hama.bundle/issues/137#issuecomment-325172277) comments/question on your proposed solutions above.

**Comment by ZeroQI** [comment]
On windows you can have:
D:\anime\...
E:\anime\...
That will be problematic given current behaviour

In some systems you can read the library name without token. Will check once back home

What scanner improvement or bugs are left to do?

**Comment by EndOfLine369** [comment]
still don't see the issue, will be:
D:\anime...   --> 'D-anime'
E:\anime...   --> 'E-anime'

**Comment by sven-7** [comment]
The latest beta seems to have broken(?) the "all in one" log approach. I have a new log structure, but it seems the HAMA part is not writing into them. Attached my full log files.

[_Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/1254477/_Logs.zip)

**Comment by EndOfLine369** [comment]
@sven-7, not broken. working on fixing logging as it does not handle when ASS/HAMA are used in more than one library or if there are more than one root in a library. Once ASS is set, HAMA will be set to match.

**Comment by EndOfLine369** [comment]
ASS will now truncate logs on rescan

**Comment by EndOfLine369** [comment]
I'm out on trying to get this work. Even with my last tweaks, it still has a case of uncontrolled log growth for non-declared grouping folder's log file. This is a bad idea.

Even if this was working perfectly, your also now requiring yourself to maintain all log files and directories (not in the code yet). As if people remove libraries, remove roots or rename/delete series folders, your left with wasted space and old files that will never get deleted. Also by not using a single rolling log file, those log files can potentially get ridiculously large. Which is what we were facing before I updated the AAS log file become rolling. I had >1GB log files which was unacceptable.

**Comment by ZeroQI** [comment]
I had multiple case of users sending me all logs and the series was not in there, or sending me logs for agent instead of scanner and vice-versa and a log per serie/folder fix it if working. 
it is also much easier to have filelist, scanner log, then agent log but a pain to maintain.

I agree by separating series, there is more logs but they are meant to be reset on rescan which keep things controlled. some will be left there after the serie was deleted, that seem acceptable, but 1gb logs are not... 
If we create a folder for logs per library and delete all files in there on root scan, that alleviate the problem, right ?

if we take the length of the code generated by the longest running serie (one piece of detective conan) we can setup rolling log as safeguard.

I will try fixing as i like the functionality.

**Comment by ZeroQI** [comment]
solved by creating separate log for scanner and agent per series with the library name as folder
Closing this thread
