### ISSUE TITLE
No metadata shown

### ISSUE THREAD

**Issue by anohren** [ZeroQI/Hama.bundle#150]
Using ASS + Hama

After manually matching a tv show and confirming that the xml (69.xml -- one piece) has been downloaded to plug-in support directory, still no metadata is shown in the plex clients.

I got it to erroneously match the show to a One Piece movie once, where it managed to show both the cover art and description, but since then, nothing. 

Titles of all the episodes etc. are listed in the log, it just seems that Hama does nothing with this info.

**Comment by anohren** [comment]
For anyone else with this problem, the metadata shows up a significant time (20 minutes?) after it has been downloaded, making it nigh impossible to determine whether a match correction/agent switch was effective or not.

**Comment by ZeroQI** [comment]
i do not care about Plex clients as if the information is on the Plex Media Server GUI then it is a plex issue and the agent is correct. If the PMS metadata information then it can be an agent or scanner issue...

If the information was not in the PMS web interface, i would need the agent logs as per the read-me troubleshooting section. there might be internal Plex delays for long series

Are you using the Beta branch?
Is the agent log which list all meta per episode showing the right info? if so that's a plex internal issue, you might want to clean/optimise the Plex database
Logs?

**Comment by anohren** [comment]
Correct, no information in the web interface. 

I agree that there are a lot of possible bottlenecks in this case. 

I'll try and reproduce it later and see if I can get you some logs.

**Comment by ZeroQI** [comment]
the agent will load xml give status and say what it updated plex with all meta indicated. if ok there, then plex oesn't update meta from the agent fast enough...

**Comment by anohren** [comment]
Let's hope that's the case so as to save you some trouble. After all, judging by its performance in some cases, Plex seems to be designed with the premise of "a season has one or more episodes... ...but surely no more than 30?" 🙂

**Comment by ZeroQI** [comment]
well it can handle a lot but might be slow to process on restricted cpu or if internal database corrupted
Could you reproduce the issue in the end?

**Comment by ZeroQI** [comment]
Please update to latest, actually fixed a couple things, and attach hama log and will correct if issue is present

**Comment by anohren** [comment]
Hi, been away from home for a while with no possibility to test. 

I'll check out the new version and reopen if the problem reappears.
