### ISSUE TITLE
Metadata only for season 1

### ISSUE THREAD

**Issue by frumpymoons** [ZeroQI/Hama.bundle#153]
I only have one anime series in my library (One Piece).
One Piece / Season XX / Episode XXX

But only the files in the Season 01 folder are getting metadata. Im using the beta branch.
At which log file do I have to look to find the issue?

**Comment by ZeroQI** [comment]
custom agent logs in agent data folder

**Comment by ZeroQI** [comment]
Please upload hama agent logs

**Comment by frumpymoons** [comment]
I figured it out. tvdb has 8 episodes in the first season, I had a lot more in there.
Is there a way where I can just create a bunch of folders and treat them not like seasons?

Example
1-100
101-200
201-300
...

My network share gets very slow if it has a lot of files in one folder.

**Comment by ZeroQI** [comment]
Tvdb4 mode use absolute numbering in any season
TVDB series [tvdb4-xxxxx]\
- [001-100] Season 1 Title Series 1
- [100-150] Season 2 Saga 2...


On 28 Nov 2017 19:31, "frumpymoons" <notifications@github.com> wrote:

I figured it out. tvdb has 8 episodes in the first season, I had a lot more
in there.
Is there a way where I can just create a bunch of folders and treat them
not like seasons?

Example
1-100
101-200
201-300
...

My network share gets very slow if it has a lot of files in one folder.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ZeroQI/Hama.bundle/issues/153#issuecomment-347637391>,
or mute the thread
