### ISSUE TITLE
Accounting for Scudlee mapping fixes

### ISSUE THREAD

**Issue by mweber03** [ZeroQI/Hama.bundle#165]
Does anything in Hama account for scudlee fixes? For example, I recently found some mismatches in the scudlee list that were merged in. If i do a fresh scan with an empty library these changes seem to be pulled in. But does anything fix it for me. For example if it was scanned in as AniDB s0e3 to TVDB s0e4, the guid is now tvdb/0/4, then scudlee's list is updated so AniDB s0e3 maps to TVDB s0e5, will anything change my guid accordingly?

**Comment by ZeroQI** [comment]
For anidb2 modes in scanner (beware of this mode), you need one change in folder so the scanner refreshes (unless in grouping folder or root, scanned every time) and the scanner will update correctly
Other mode have the ep number fixed

You need to refresh meta one weeks after the correction due to caching and Hama will update the meta correctly if the meta mapping changed.

Guid is serie based not file based
