### ISSUE TITLE
Movies not being recognized

### ISSUE THREAD

**Issue by Brian-Graham** [ZeroQI/Hama.bundle#20]
![]
(https://i.netcoding.net/43ec41e2.png)

That is the information popup for the first episode of bleach (Season 1, Episode 1). It is lugging in the file from Movies/ and the one you've said to use for recognizing a movie.

Plex has a custom Specials folder for OVAs / Special files, is there not a way to create a Movies folder?

When I try [1] Movie Name.ext, it does not match to it at all.

**Comment by ZeroQI** [comment]
Seem like s01e02, looking at your filenames it work as designed
I failed to see a separate folder for each movie using anidb numbering or name the movies as per thetvdb like s00e14...
Since there is no check before the ep number they get grouped in the ep number.
Please quote exactly how i said to do it because inside a movie folder isn't it.

I could consider in the scanner Movies as specials folder or as specials with an offset episode number but no netadata that way...

My agent is an anidb and tvdb metadata agent. You followed neither in numbering them.

**Comment by Brian-Graham** [comment]
Is there anyway to make a custom folder like "Specials" but for movies (called Movies)?

As well, my absolute numbered episodes in different season folders in Bleach aren't being found correctly. There is no title / meta information after Season 1.

**Comment by ZeroQI** [comment]
1. Not in the agent. In the scanner how to link with movie metadata?
2. One folder per movie named like the file bar the extension.  Label movies s00exx as per thetvdb specials since you use seasons then tvdb ascmetadata source
3. It's because it is not season numbering since ep number doesn't start at 1... just leave all eps in root and put a tvdb.id file with the tvdb id for the serie inside and plex will show seasons. If you rename ep 42 as s03e01 it works. The agent works as designed.

**Comment by Brian-Graham** [comment]
1. Yes. I'd like to have it custom scan a "Movies" folder for movie metadata, is it possible and how can I do it?
2. Can you show me an example, using Bleach The Movie: Memories of Nobody inside a Bleach series folder?
3. Can I modify the scanner or agent to default back to absolute scanning if the first file is not episode 1 inside a season folder? (This way I can preserve proper looking folder structure, but still keep absolute episode numbers, because large shows like Bleach, Naruto and Detective Conan have wiki pages for the absolute episode numbers, and I don't like a massive file count in one folder.)

**Comment by ZeroQI** [comment]
1. It already process the folder but implying season 1 so you have to explicitely says season 0.
2. Bleach/Specials or Movies/Wharever it's skipped s00e03 Bleach The Movie Memories of Nobody.ext
3. I call that hybrid numbering. You can either modify the scanner to stsrt at 1 or the agent to detect it is hybrid numbering. I think i did some code in the agent to allow that will need to check, but realise that what you want is not following any convention and i am pretty sure  nobody dupport thit yet in any platform xbmc/kodi or media browser... Aldo if a season 2 has more eps than season 1 you can't add hybrid details to tge mapping table you have to detect it...
