### ISSUE TITLE
Ajin 2 (2016) [anidb-12111] title problem.

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#226]
**Folder Name:** Ajin 2 (2016) [anidb-12111]
**Title Language Preferences:** en, main, ja
**Title Sources:** AniDB, TheTVDB

**Problem:** Sort title is correct, while title is not correct
![image](https://user-images.githubusercontent.com/14930057/41964526-1c6f45ba-79f2-11e8-81a5-5285aa10503e.png)

**Logs:**
> [x] title                          Sources: AniDB,(TheTVDB)                                               Inside: '['MyAnimeList', 'TheTVDB', 'AniDB']'  Value: 'Ajin'
[x] title_sort                     Sources: (AniDB),TheTVDB                                               Inside: '['TheTVDB', 'AniDB']'  Value: 'Ajin 2 (2016)'

Something to do with #213 ?

I guess the logic here is, since there's no "en" title on AniDB, it tries the second source TVDB. The logic is "fine", but the problem is that since this is a second season, TVDB titles are not different by seasons and it gives just the title of the first season which I already have on another entry.

There should be an option where you can force Hama to get any title by the order of language from the first source, so in this case, it would get the "main/ja" title from AniDB, before going to TVDB.

This used to be correct before, both the Sort Title and Title would be the same.

**Comment by ZeroQI** [comment]
it takes languages first, per source order, so will take english title from AniDB, then TheTVDB, if not found, x-jat from AniDB, then Japananese from AniDB then TheTVDV
Please use "x-jat" instead of main.

Where are the logs about language priority ? Pretty sure i indicate per source te language which had the highest priority (index of language in the language priority order so lower mean highter priority)

> There should be an option where you can force Hama to get any title by the order of language from the first source, so in this case, it would get the "main/ja" title from AniDB, before going to TVDB.

Definitely not. it took multiples month of coding and rewrite to have the agent at a point where you can say chinese first as language, and it takes it from any source, as it should (needed multiple anidb mxl loading support among other things)

**Comment by KurtzPT** [comment]
I understand your logic, but the title from TVDB when the season is >1, is always wrong. TVDB always assumes the 1st anime title as all titles for all seasons, and that's 99% of the times, wrong.

At least, I think a fail safe mechanism could be coded in Hama that in the case an anime season maps to >1 on TVDB, it should ignore those titles, (in case there's more sources, and if these sources have titles of any of the languages in preferences)

**Comment by ZeroQI** [comment]
Thanks for the constructive discussion, i have little free time and will have less and less as building a house and sometimes it is tricky fixing as the code grw quite complex....

So in short, for series with AniDB id assigned , TheTVDB title for seasons not 1 when AniDB present as source in the title field metadata source list will be set to the lowest priority of all (len(language_priority) instead of the language index in the language_priority list, so after all set languages (in case a remote serie have one title in the language in thetvdb, better than no title). should set main title as fallback in AniDB too.

**Comment by KurtzPT** [comment]
Confirmed it's fixed on this Ajin 2 (2016) [anidb-12111]
