### ISSUE TITLE
Remove "based on" text from AniDB descriptions

### ISSUE THREAD

**Issue by rcdailey** [ZeroQI/Hama.bundle#232]
Series description for almost all anidb TV shows looks something like this:

> \* Based on a comedy seinen manga series written and illustrated by Ootake Masao.
>
> One night, a strange object falls on the head of Nitta, a member of the yakuza. Inside the box is a strange young girl named Hina. She has tremendous supernatural powers, and Nitta finds himself reluctantly taking her in. Her powers can come in handy for his yakuza business, but he also runs the risk of her using them on him! Not to mention, if she doesn't use her powers, she will eventually go berserk and destroy everything around her. Nitta and Hina's strange life together is just beginning...

([Link](https://anidb.net/perl-bin/animedb.pl?show=anime&aid=13434))

It would be nice if the `* Based on a comedy seinen manga series written and illustrated by Ootake Masao.` as well as any blank lines after it get stripped by the agent. Reason I'd like to see it removed is that it pushes the meaningful description down too far when viewing it through Plex. It's basically a whole 2 lines of wasted space.

Not sure if you agree or not, or whether or not this could be reliably done with some sort of regex (maybe any lines starting with `* `?).

**Comment by ZeroQI** [comment]
@rcdailey I suppose i can make it an agent setting option: 'AniDB sumnary note removal'. Will do at the week end

Are you using a phone/tablet as the web page should have pleinty space?

**Comment by purposelycryptic** [comment]
I don't suppose you could have it remove Summary Source Citation too?
i.e.,

>Uranohoshi Girls' High School, a private school in the seaside neighborhood of Uchiura at Numazu city, Shizuoka prefecture.
>
>A small high school in a corner of Suruga Bay, it is home to nine teens, led by second-year student Chika Takami, driven by one seriously big dream:
>
>To become the next generation of bright, sparkling "school idols"!
>
>As long as we don't give up, any dream can come true...
>All we have to do now is keep pushing hard for glory!
>
>Now their "School Idol Project" begins to make their dreams come true!
>
>**Source: crunchyroll**
>
([Link](https://anidb.net/perl-bin/animedb.pl?show=anime&aid=12897))

It's always at the end, and always in that 'Source: XXXXXXXX' format. The Plex WebUI just allocates way too little space for series' summaries (See [here](https://imgur.com/SZ85gjy) for example) :-/

**Comment by sven-7** [comment]
Interesting idea. That’s exactly why I have it set to order TVDB series descriptions over AniDB. If the AniDB ones could get cleaned somehow, that’d be a clever feature.

**Comment by EndOfLine369** [comment]
All you need is `"^(\* Based on |Source: |Note: |$)"` where 'string' = '\<description\>' tag text.
And used in something like the below line.
`"\n".join([line for line in string.split("\n") if not re.search("^(\* Based on |Source: |Note: |$)", line, re.IGNORECASE) ])`
EX:
```python
>>> string = """* Based on a four-panel romantic comedy manga by http://anidb.net/cr52647 [Nekoume].
... http://anidb.net/ch92320 [Shiina Aki] is constantly being treated like a girl due to his feminine looks so he decides to move to Tokyo and attend middle school in an attempt to change himself.
... However what awaits him in his new home, Sunohara-sou, is the kind-hearted caretaker, http://anidb.net/ch92318 [Sunohara Ayaka] and three female members of Aki`s new middle school`s student council, named http://anidb.net/ch95079 [Yukimoto Yuzu], http://anidb.net/ch95078 [Yamanashi Sumire], and http://anidb.net/ch95080 [Kazami Yuri].
... And so begins Aki`s new life of living with four girls in Tokyo.
... Source: M-U
... Note: The complete edition with something"""
>>>
>>> "\n".join([line for line in string.split("\n") if not re.search("^(\* Based on |Source: |Note: |$)", line, re.IGNORECASE) ])
'http://anidb.net/ch92320 [Shiina Aki] is constantly being treated like a girl due to his feminine looks so he decides to move to Tokyo and attend middle school in an attempt to change himself.\nHowever what awaits him in his new home, Sunohara-sou, is the kind-hearted caretaker, http://anidb.net/ch92318 [Sunohara Ayaka] and three female members of Aki`s new middle school`s student council, named http://anidb.net/ch95079 [Yukimoto Yuzu], http://anidb.net/ch95078 [Yamanashi Sumire], and http://anidb.net/ch95080 [Kazami Yuri].\nAnd so begins Aki`s new life of living with four girls in Tokyo.'
>>>
```

**Comment by purposelycryptic** [comment]
@EndOfLine369 
I appreciate you posting a nice and clean implementation, though I found myself unable to successfully get it working - this being my first attempt at anything Python :-| -and also, and I could very very well be wrong here, so my apologies if I am, but I think it should be single quotes around the Regex part, i.e.,:

```python
"\n".join([line for line in string.split("\n") if not re.search('^(\* Based on |Source: |Note: )', line, re.IGNORECASE) ])
```

Anyway, I ended up just integrating it into the "Internal AniDB Link Removal" function in_init_.py, as:
```python
description = re.sub(r'http://anidb\.net/[a-z]{1,2}[0-9]+ \[(.+?)\]', r'\1', re.sub(r'^\* B.*\n+|\nSource:\w*[\w\W]*()', r'\1', getElementText(anime, 'description'))).replace("`", "'")
```
And, since there was a highly similar function in AniDB.py, the same there, just in case:
```python
> if SaveDict( re.sub(r'http://anidb\.net/[a-z]{1,2}[0-9]+ \[(.+?)\]', r'\1', re.sub(r'^\* B.*\n+|\nSource:\w*[\w\W]*()', r'\1', GetXml(xml, 'description'))).replace("`", "'"), AniDB_dict, 'summary')
```

And it seems to work as intended without affecting the original function, i.e.:

Raw AniDB Summary:
![Raw AniDB Summary](https://i.imgur.com/B0XXL2b.jpg)

Processed AniDB Summary:
![Processed AniDB Summary](https://i.imgur.com/Y9FzgUk.jpg)

It's mainly beneficial when the summary isn't expanded, as in this (Pre-Change):
![Pre-Change](https://i.imgur.com/KDBYuZf.jpg)
Vs. this (Post-Change):
![Post-Change](https://i.imgur.com/jRPvCuh.jpg)

Since I don't really know what 'm doing, I wasn't entirely sure how your implementation would affect the paragraph spacing, whether it would remove all blank lines, or leave the ones before/after the cut parts, or end up the same as mine (remove before/after cuts at bottom/top, respectively, but leave paragraph breaks). I really wanted to preserve the paragraph breaks but remove the rest, and since I couldn't get your version to run until I had essentially finished mine (And realized the single-quote RegEx issue), here we are.

Great learning experience :-)
...although I spent at least two hours trying to trouble-shoot the stupid thing because I didn't know that Python takes issues with Tab indentation, which Notepad++ was automatically inserting... So, yeah... like I said, this is all new to me.
