### ISSUE TITLE
Getting banned logs by accessing anidb for some series

### ISSUE THREAD

**Issue by miracle152004** [ZeroQI/Hama.bundle#257]
Hi,

getting the meta data for some series on anidb writes a banned error message in the logfiles an do not download the metadata.

Accessing the http-Address with the browser works.
Getting the metadata for other series works.

Here a excerpt from the logfile:
2018-10-30 19:46:48,407 (26f0) :  INFO (logkit:16) - AniDBid: 13170, url: http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=13170
2018-10-30 19:46:48,446 (26f0) :  DEBUG (networking:161) - Fetching 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=13170' from the HTTP cache
2018-10-30 19:46:48,486 (26f0) :  INFO (logkit:16) - [!] File received too small (<64 bytes), file: "<error code="500">banned</error>"
2018-10-30 19:46:48,486 (26f0) :  INFO (logkit:16) - LoadFile() - not xml nor json: None 

Could you please take a look.

Thanks

Best regards
miracle152004

**Comment by EndOfLine369** [comment]
If you've gotten banned at any point in the last few days, it will keep that banned response in the Plex cache for I believe 6 days. You will either have to wait for it to timeout in the Plex cache or search in a 'fix match' window for 'clear-cache' and it will clear out the Plex cache. You will get back a match item of 'Plex web cache cleared' and just cancel the match window.

**Comment by ZeroQI** [comment]
normally the length of file is tested to not be cached locally but might stay in Plex cache, however it should load the local cached file if one existed before the ban, at least if i coded it correctly

**Comment by ZeroQI** [comment]
extract from pull request chat.

> Looks like AniDB is just making itself set to ridiculously low thresholds on ban requirements now. Can't do more than 50-60 if you don't want an eventual ban. Otherwise, its a try as fast/long as you can to get as many as you can till you get banned. You would potentially have to set it to 30-60sec....maybe.... Biggest problem is no definition on what will get you banned.
> 
> Was just frequency and number of times of same request. Not the case now and documentation not updated on what has changed. They seem to have added not liking you getting too many or for trying for too long from what I can tell.
> https://wiki.anidb.net/w/HTTP_API_Definition#Flooding_and_Caching
> 
> Basically a leeching overreaction.

Shall we close this bug report?

**Comment by hergonoway** [comment]
I'm exactly in the same situation, I've scripted my NAS to move 1 anime folder per minute to the target library folder scanned by Plex and has been banned around 180/200 Anime. 

Since my title params are set to "Anidb | TvDB, Anidb"  and Anidb in top priority for posters, I get a black entry in plex with the folder name as title once banned. 

Until we gathered further information from Anidb staff about their IP temp ban over public API, I've wanted to know how is handle this ban state with the agent. 

For example, I've got 500 shows were I was ban during their addition to the library, so black poster and title is folders name. So I've got on my 1000 shows library half of it just not well scrapped. If I just wait days and days will it fix by itself through automatic metadata refresh and Plex maintenance operation. 

Anidb's API call answering "banned" cause quite a ruckus in the logs.

**Comment by EndOfLine369** [comment]
@hergonoway, it is handled. That is what the other data sources are for as well. There is no way around AniDB ban hits, as the triggers are not stated and will never be stated. As people that are trying to leech will just work around knowing that info like we want to.

It is also fully handled if not a fresh install. As once you've pulled the xml data once, it will always be there. Just potentially not up-to-date if you get banned. But it will successfully load the older data.

You will either need to leave it to the Plex auto refresh gradually over time. Or after each un-ban, clear the plex cache & refresh again. You can try a full refresh each time BUT if not complete in 6 days, you will need to start selecting the series to refresh at that time. As the cached xmls will be aged and be tried to be pulled again from AniDB and hit a ban before it gets to the still unreached entries.

And logs are just fine as it is. As it clearly states your issue from an AniDB pull for each try/series.

@ZeroQI, sounds like a close as nothing we can do here as we have no control over AniDB site's behavior and we now have better logging in place & ways to handle when banned of loading old cached info or other sources.

**Comment by hergonoway** [comment]
Fun fact, I'm currently ban IP on public API, but not on the authentifed endpoint. (Aniadd still working)

Maybe handling Anidb account could reduce (a least a bit) the ban constrain. 

Of course it's an assumption since no one in Anidb's staff want to communicate about ban rules on there public neither on their authentified endpoints.

**Comment by ZeroQI** [comment]
it's two separate API though http and udp or tcp, the agent is super complicated already...
We need to narrow down reqirements and make sure not 2 calls for same series xml is done per day and space time between requests. Happen only when re-creating libraries and clearing cache to me...

**Comment by hergonoway** [comment]
Makes sense, didn't know the complexity of their API. 

Well if one day you go for it, add the "add to mylist" while your at it :p
