### ISSUE TITLE
Another mapping issue

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#291]
**Anime:** Dragon Ball Z Special Tatta Hitori no Saishuu Kessen - Freezer ni Idonda Z Senshi Son Gokuu no Chichi [anidb-2336]
**AniDB:** https://anidb.net/perl-bin/animedb.pl?show=anime&aid=2336
**TheTVDB:** https://www.thetvdb.com/series/dragon-ball-z/seasons/0
**Log:** [Dragon Ball Z Special Tatta Hitori no Saishuu Kessen - Freezer ni Idonda Z Senshi Son Gokuu no Chichi [anidb-2336].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/2975358/Dragon.Ball.Z.Special.Tatta.Hitori.no.Saishuu.Kessen.-.Freezer.ni.Idonda.Z.Senshi.Son.Gokuu.no.Chichi.anidb-2336.agent-update.log)

**Mapping:**
```
  <anime anidbid="2336" tvdbid="81472" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="tt0142245">
    <name>Dragon Ball Z Special: Tatta Hitori no Saishuu Kessen - Freezer ni Idonda Z Senshi Son Gokuu no Chichi</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-14;</mapping>
    </mapping-list>
  </anime>
```

It should map to S00E14 in TheTVDB, but it's mapping to S00E01.

**Comment by ZeroQI** [comment]
`if anidb_numbering:  season, episode, anidbid = anidb_ep(mappingList, season, episode)`
```
mappingList: {
  'TVDB': {
    's0e14': ('1', '1', '2336'), 's-1': {'2336': '0'}},
  'defaulttvdbseason': '0',
  'episodeoffset': '0',
  'imdbid': 'tt0142245',
  'name': 'Dragon Ball Z Special: Tatta Hitori no Saishuu Kessen - Freezer ni Idonda Z Senshi Son Gokuu no Chichi',
  'season_map': {'2336': {'max': '0', 'min': '0'}},
  'tvdbcount': 1}
```
anidb_ep(mappingList, 0, 14) should return ('1', '1', '2336'), make no sense to me

**Comment by EndOfLine369** [comment]
@KurtzPT, you put the episode into Plex as `anidb-2336/s0e1` as seen in the meta update in the log
`metadata.seasons[ 0].episodes[  1]`.
You should be putting it as `anidb-2336/s1e1` into Plex as this is the only/first episode in the AniDB series.

**Comment by EndOfLine369** [comment]
@ZeroQI 

> anidb_ep(mappingList, 0, 14) should return ('1', '1', '2336'), make no sense to me

It does return correctly `[ ]   s0e14 s01e001 anidbid:    2336 air_date: 1990-10-17`

> no AniDB section in logs

Yes there is but as incorrect season/episode was put into Plex (s0e1 instead of s1e1), nothing is seen as added into Plex.
```
--- 2336.episodes -------------------------------------------------------------------------------------------------------------------------------------------
[ ] ep creators (creators tag): {}
[ ] s1e  1 => s1e  1 air_date: 1990-10-17
[ ] s0e201 => s0e201 air_date: 
```

**Comment by ZeroQI** [comment]
@EndOfLine369 : Not used to new logging, but it's good and very thorough, i would remove line feed and shorten summary if too long for eps. (example below)
```
[X]    s0e1 s00e001 anidbid:         air_date: 1989-07-15 abs_number: 0, title: Dead Zone
 - [ ] summary: Gohan has been kidnapped! To make matters worse, the evil Garlic Junior is gathering [...]

 - [1] language_rank: 0, language:   en, title: Dead Zone
       common.SaveFile() - CachePath: 'C:\Users\Admin\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems', file: 'TheTVDB/json/81472\episode_411405_ja.json'
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/81472/411405.jpg
[ ]   s0e14 s01e001 anidbid:    2336 air_date: 1990-10-17
```
Using anidb numbering, does have a cross to indicate the file s0e1 was detected, but none for s1e1

@KurtzPT did you casually forgot to mention the movie is detected by the scanner as s00e01 instead of s01e01 and furthermore created an agent issue ticket instead of a scanner one?
- series folder "Dragon Ball Z Special Tatta Hitori no Saishuu Kessen - Freezer ni Idonda Z Senshi Son Gokuu no Chichi [anidb-2336]"
- file "Dragon Ball Z - TV Special 01 (HD Remaster) [Puto][61335219].mkv" so "Special 01" would be detected as s00e01. 

You did not name the file accurately for a movie in a series library, closing this.

**Comment by KurtzPT** [comment]
> * file "Dragon Ball Z - TV Special 01 (HD Remaster) [Puto][61335219].mkv" so "Special 01" would be detected as s00e01.

Just to make it clear, when you say it's detected as s00e01 it's on the anidb logic part, so it would not follow the mapping above since that mapping is just for season 1, is that correct?

I actually didn't rename the file, that's the original filename. What I didn't know is that by having "TV Special" it would automatically detected as S00, because that does not make much sense to me, as in this case its a tv special and not automatically a S00 file.

**Comment by ZeroQI** [comment]
I documented in the scanner readme: "Movies in series library support (names same as folder or contain " - Complete Movie")" and since it wasn't followed, the movie was detected as season 0 as the scanner sees a special and put in the Specials season (0).

You created 35 tickets so far, please consider donating if not done already
