### ISSUE TITLE
rewrite metadata in Spanish?

### ISSUE THREAD

**Issue by PWalll** [ZeroQI/Hama.bundle#315]

**Comment by ZeroQI** [comment]
No exemple, explanations, anything you tried, where you want the Spanish titles to come from ?

Cannot even tell if a bug or feature request or even reproduce....

Tried putting spanish 'sp' first in agent settings for language selection and full library metadata refresh?

I had entitled people creating bug reports and some with bad naming conventions not wanting to rename files, but creating a bug report with NO description instead of asking the forum for assistance for what seem a usage query when we are already loaded in bug reports is for me single handlely the most disrespectful bug report to date...

**Comment by PWalll** [comment]
Sorry for my stupidity. I mean to put on the website a translation, contributed by fans, and then in plex to choose one of the languages.

**Comment by ZeroQI** [comment]
If you select 'sp' for the library language setting all summaries will be in that language.
If you go in agent settings and put 'sp' in priority then the titles in Spanish in AniDB and TheTVDB depending the source order will be updated if available in Spanish when doing a full metadata refresh.

If it doesn't work and Spanish summaries after a metadata refresh, and titles are available in either AniDB or TheTVDB, paste the series agent logs as a file hère and would reopen then.

Please speak in Spanish (or French) for further replies as I am not sure what you mean by 'contributed by fans' in your last message.

Orguilloso de estar en en proletaria, es difficil llegar fin del mes y sudar y sudar para ganar nestro pan...

**Comment by PWalll** [comment]
Me refería a hacer contribuciones tipo Wikipedia.

**Comment by ZeroQI** [comment]
Puedes hacer uba contribucion a AniDB y TVDB (especialmebte esta) y el
agente va a utilizar en castellano el titulo de la serie, de los episodos y
le resumen...

**Comment by PWalll** [comment]
Where I put the SP in options?

**Comment by ZeroQI** [comment]
Library language for summaries and for titles Plex agent settings (language order priority is the main criteria, then source order for titles in series|episodes). it will take the source in order per language until it find a match, so if you have half of titles for eps in anidb and the exact other half in spanish in thetvdb, all l will be with spanish titles if it is first in language priority
