### ISSUE TITLE
Hama Agent not working.

### ISSUE THREAD

**Issue by letthiswork1** [ZeroQI/Hama.bundle#327]
Hi,

Hama Agent has not been working for quite some time.

Example of not pulling info - https://gyazo.com/01f1f846cf417754f38e524651f01a54

originally it was an issue with the absolute series scanner.pyl file being corrupt and downloading a new version and installing would work but it seems like that's not the case anymore.

If i change the scanner to TVDB it works fine in plex client.

I am not overly skilled with the agent are you able to advise what went wrong?

Also your Donation link is not working. I was able to donate previously

Thanks

[_root_.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3440601/_root_.scanner.log)
[_root_A -Anime.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/3440602/_root_A.-Anime.filelist.log)
[_unknown_folder.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3440603/_unknown_folder.agent-search.log)
[_unknown_folder.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3440604/_unknown_folder.agent-update.log)

**Comment by ZeroQI** [comment]
First, thanks for pasting logs on first post.

The agent cannot get the library name, root folder nor the path for logs so put all in the logs interleaved so cannot read them, not sure if it also cause your issues...

First update both scanner and agent as there were changes in anidb title file causing all users issues with previously working agent...

You should Place a Plex token string in file in Plex root '.../Plex Media Server/X-Plex-Token.id' to have a log per library per series. You can get your plex token here:
https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token

after it may solve or if not, you will have logs per series and i need the search and update logs of one not working

I am having an issue with Paypal, my pc was hacked and 29 transactions of 89.99€ were done from my IP (remote access trojan seemingly) and have been trying to correct that since... They aknowledged it should have been accepted as unauthorised transactions and reversed 10 days ago, should be solved by next week...

**Comment by letthiswork1** [comment]
Thanks for your switft reply!

i re-downloaded the python scanner and the agent from your git and installed them and now refreshing all Meta Data.

Regarding the Token String. I read the guide but the URL does not seem to show the string.

Local Host URL to anime Library - http://127.0.0.1:32400/web/index.html#!/server/bd6a02d9e4482e37d86f46d0881c52cd907a0743?key=%2Flibrary%2Fsections%2F4

Remote URL to Library - https://app.plex.tv/desktop#!/media/bd6a02d9e4482e37d86f46d0881c52cd907a0743/com.plexapp.plugins.library?key=%2Flibrary%2Fsections%2F4&context=content.library&source=%2Fhubs%2Fsections%2F4

Also i dont see an option to view XML. only view source but no reference there to X-Plex-Token.

Sorry to hear about the Trojan... please let me know when its fixed as i really appreciate what you do

**Comment by ZeroQI** [comment]
You go to your library, a series, a season, then an episode (without viewing, the ep metadata page), click on the three dots, then "get info" at very bottom, then on the popup page at the bottom "view xml" and it is in the url then, for me: http://127.0.0.1:32400/library/metadata/741?checkFiles=1&includeExtras=1&includeBandwidths=1&X-Plex-Token=U_xcxxxxxxxxxxxxxxx

**Comment by letthiswork1** [comment]
Hi @ZeroQI  i refreshed the Metadata but still same issue :(

**Comment by letthiswork1** [comment]
Starting to think i am blind...

Went to an episode - https://gyazo.com/6909aebc5ee029147d6e6d13c09e1966
View XML - https://gyazo.com/76ff314663bc7367f5c11be473e23a45
No token string - https://gyazo.com/c44c932aeb32c97d4cfeab83328d59da

**Comment by letthiswork1** [comment]
wow ignore my last post i was blind!

**Comment by ZeroQI** [comment]
yes. that should allow the agent to load the library file to have library name and root folder.
It should on metadata refresh create logs in a folder with the library name per series.
I need the logs for an impacted series

**Comment by letthiswork1** [comment]
Hi,

I did a refresh still nothing and the token file is empty.
Is this correctly setup?

I censored some of the ID

https://gyazo.com/41a36a046de97479afccbf27ecfed68e

**Comment by ZeroQI** [comment]
faire un match manuellement puis récupérer ces logs:
- Logs/Library/series.search.log
- Logs/Library/series.update.log

**Comment by sakuyaslove** [comment]
FYI, I just came here because I haven't added any anime for a while but I just did and it wasn't fetching.

I downloaded the repo fresh, removed Hama.bundle from plugins and re added it from the downlaoded repo and went to scanner file (https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/Scanners/Series/Absolute%20Series%20Scanner.py) and coppied all the info and replacesed the info inside the Absolute Scanner.py file with it, restarted plex and refreshed metadata on the new anime I added and it worked perfectly.
