### ISSUE TITLE
Hama not pulling titles with colons in their name.

### ISSUE THREAD

**Issue by Renari** [ZeroQI/Hama.bundle#331]
e.g.

https://anidb.net/anime/13829

`Party: Banquet of the Gods`
gets pulled as
`Party`

**Comment by ZeroQI** [comment]
"Party Banquet of the Gods" should work.
using latest version?
custom *.search.log series Logs in agent data folders missing

**Comment by Renari** [comment]
Here's the relevant log files, I also noticed that it's probably not getting the data from anidb, I'm not sure where it's getting the data from since episode 2 is showing `Aporon` which doesn't show on anidb or tvdb.
[DanMachi.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3459862/DanMachi.agent-search.log)
[DanMachi.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3459863/DanMachi.agent-update.log)
[Dungeon ni Deai o Motomeru no wa Machigatte Iru Darouka: FAMILIA MYTH II.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3459864/Dungeon.ni.Deai.o.Motomeru.no.wa.Machigatte.Iru.Darouka.FAMILIA.MYTH.II.agent-search.log)
[Dungeon ni Deai o Motomeru no wa Machigatte Iru Darouka: FAMILIA MYTH II.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3459865/Dungeon.ni.Deai.o.Motomeru.no.wa.Machigatte.Iru.Darouka.FAMILIA.MYTH.II.agent-update.log)

**Comment by ZeroQI** [comment]
You create a bug report for "Party: Banquet of the Gods" that gets pulled as "Party" and attach logs for "DanMachi" (anidb api loaded ok) and "Dungeon ni Deai o Motomeru no wa Machigatte Iru Darouka: FAMILIA MYTH II" that was searched with string "danmachi2" (anidb api loaded ok) so useless to the issue reported in the title...

"I'm not sure where it's getting the data from" seriously??? i coded for days to have a log showin per episode PER FUCKING FIELD the output:
```
Anidb
[X] s1e  2 => s1e  2 air_date: 2019-07-20 language_rank: 0, title: "Aporon"

Engine output
metadata.seasons[ 1].episodes[  2]
[?] rank: 0, source_title:   AniDB, title: "Aporon"
[=] title                          Sources:  TheTVDB, AniDB| TheTVDB, (AniDB)                             Inside: '['AniDB']'  Value: 'Aporon'
```

rank 0 so first language title selected
Logs show for AniDB api url "http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=13829"
```
<episode id="217977" update="2019-06-11">
<epno type="1">2</epno>
<length>25</length>
<airdate>2019-07-20</airdate>
<rating votes="2">7.60</rating>
<title xml:lang="ja">太陽神[アポロン]</title>
<title xml:lang="en">Apollo: Sun God</title>
<title xml:lang="x-jat">Aporon</title>
<resources>
<resource type="28">
<externalentity>
<identifier>787160</identifier>
<identifier>is-it-wrong-to-try-to-pick-up-girls-in-a-dungeon</identifier>
</externalentity>
</resource>
</resources>
</episode>
```

title is from x-jat (romaji) title. the language is firt criteria in the order by source so if you select chinese, it will pick a chinese titke in the source order...

Closing bug report
- no logs to substantiate error reported
- second issue reported when all the information is in logs pasted...

**Comment by Renari** [comment]
Sorry but I didn't check the API, I checked the website like most people would using the link provided. I didn't even know the existence of these logs until you asked for them. Furthermore there was nothing in the readme mentioning the logs or how the names get resolved as you mentioned here.

Also your donation link is broken btw.

**Comment by ZeroQI** [comment]
Troubleshooting steps in the readme are generic but the last part of it does includes the naming convention for series log :
```
including all the following logs: (location: https://support.plex.tv/hc/en-us/articles/200250417-Plex-Media-Server-Log-Files)
[...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.hama.log (Agent logs)
[...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.system.log (show why the agent cannot launch)
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/root_folder.filelist.log (episodes info)
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/root_folder.scanner.log (episodes info)
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/root_folder.agent-search.log (guid assignment)
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/root_folder.agent-update.log (metadata update)
Screen capture to illustrate if needed. Above logs are still mandatory
```
If you create a plex token it will put logs in a folder carrying the library name, that part is not written to be fair...

The last part of the series update log show all meta and the source, i believe it to be clear and self explanatory

I can understand language part is less logical but language had to take precedence over source so that if you select a language for titles they are taken in that language first. I believe it was explained in the readme by:
`The titles priority can have the usual languages 'en', 'fr', 'sp', 'ja', etc... and the following for asian languages The titles will be in the priority indicated first and secondarily by the metadata source`

For PayPal, my PC was hacked with a remore access trojan the 11th of June and 29 transactions for 89.99 and Paypal refused the initial ticket and appeal, and executive escalation aknowledged it should have been accepted, pending for them to resolve the issue, my account is limited in the meantime and unusable, it's been a nightmare (among other things like house and car issues [stolen twice, head gasket], my friends nicknamed me black cat as a result as it's a bad luck omen)...

My nas (DS1815+) died (Intel clock degradation) and got an 100 Ohm resistor to fix (pending on electonically minded friend with good soldering iron), which is not helping with Plex, which i don't even use to watch stuff myself...

**Comment by ZeroQI** [comment]
Donation link fixed
