### ISSUE TITLE
Fetch metadata from AniList?

### ISSUE THREAD

**Issue by Luro02** [ZeroQI/Hama.bundle#341]
The API is easier to interact with and doesn't limit your traffic to 1 package every 4 seconds (https://wiki.anidb.net/w/UDP_API_Definition#Flood_Protection). (it's 90 packages per minute on AniList).

https://anilist.gitbook.io/anilist-apiv2-docs/

**Comment by ZeroQI** [comment]
http://thexem.de/xem/show/4167 gets mapping anidb, tvdb, scene
i use SudLee's AnimeList https://github.com/ScudLee/anime-lists

You provide no mapping to and from AniDB and to and from TheTVDB, no indication of the identifiers usable (tmdb) so unusable for me
Feel free to use my empty agent template and code a plex Anilist metadata agent 
https://github.com/ZeroQI/Hama.bundle/releases/download/v1.0/Empty_Agent_template.bundle.7z

**Comment by purposelycryptic** [comment]
Just saw this issue, and, while it's slightly off-topic, I've been thinking for a while about starting a fork of the ScudLee anime-lists that would include AniList mappings, once my health has improved somewhat (atm, I'm still mostly useless ¯\_(ツ)_/¯) - not for metadata (since AniDB already has more, more detailed, and more accurate data), but for scrobbling to AniList.

I mainly thought of it because it is already possible to export your AniDB MyList, and then import it to MAL (with reasonable accuracy), so there should be some form of mapping for that already, and you can export your MAL list for import into AniList (that's how I got my MyList into AniList in the first place), meaning a large part of the work should already be done in some form, and the largest challenge would be creating a way to adapt that in a way that can then be dynamically updated over time as new additions are made.

Of course, it's not nearly as simple as I'm making it sound, because nothing ever is; there are a number of hurdles, the biggest one probably being that AniList classifies series specials as their own, separate series entry, which is something that isn't mapped (or at least, doesn't survive the AniDB -> MAL -> AniList import/export chain), and so would require thousands of manual mappings. Also, lesser issue, but, while I've thought of various mapping structures, I still haven't settled on what would work best, since, up until now, the mappings have all been one-to-one/many-to-one AniDB to TVDB, etc, whereas this would be one-to-one/one-to-many AniDB to AniList.

Anyway, as you can probably tell, this is still very much in the planning stage, and is all based on the assumption that my health actually *does* improve (since I can't do anything if I'm dead), which, even optimistically, probably won't be this year, and, if it is, I'll still have rehab etc to go through. But this seemed like a good place to mention it, at least, even if AniList likely wouldn't add much as a metadata source, since that has never been a significant objective for them to begin with.

**Comment by Luro02** [comment]
The AniList api supplies you with the myanimelist ids. This means, that every id is already mapped.

**Comment by Luro02** [comment]
I hope you will get well soon. 🤗

**Comment by ZeroQI** [comment]
Get well soon

**Comment by purposelycryptic** [comment]
Thanks for the kind words😊

 > The AniList api supplies you with the myanimelist ids. This means, that every id is already mapped.

Awesome - I hadn't really looked into that part of the API yet (had mostly focused on scrobbling for a different project, trying to automatically set completed series to re-watching when an episode is played), but that potentially solves one part of the equation (or at least provides a solid hook to dig into) - given all the issues with the official MAL API, or rather, it's fluctuating existence and functionality, the AniDB -> MAL part feels like it will be a little more work, but I always assume the worst in these cases, and it could just as well be incredibly simple.

For now though, time for sleep - I really should have been sleeping for two hours already, but now I can barely type, so it's definitely time.
