### ISSUE TITLE
Metadata or cache migration between server

### ISSUE THREAD

**Issue by hergonoway** [ZeroQI/Hama.bundle#357]
Hi, 

I’m planning to add my anime library to my 2nd server but I’m too familiar with Anidb ban to basically create a library in Plex and let Hama perform a fresh check for metadata. I’ve got around 1200 anime series :/ 

My 2nd server is already running and  doesn’t have the same libraries for other content which is not anime so I can’t just tar #PlexPath#/Library/ from one server to another :/

I wanted to know if there’s a way to copy Hama cache or metadata from server 1 to server 2 so when I create my new library on server 2 Hama will get its metadata mainly from cache so I won’t be banned in 5 minutes :)

Sorry if my request sounds a bit crazy :)

**Comment by ZeroQI** [comment]
That's not a bug report, so I would have raised the question on the forum so it let other users reply...
Now it's far from being crazy, i had way worse...

Yes you can copy all in agent data folders, it's only cache, that's why i did it explicitly in the first place. Put back the same agent settings

You could even use Lamda to put the metadata along the media and load it back, but i would do tests beforehand if going that route
