### ISSUE TITLE
[anidb-xxx] tag mismatch : use some tvdb infos instead using only anidb info for specials episodes

### ISSUE THREAD

**Issue by StudioEtrange** [ZeroQI/Hama.bundle#362]
**Abstract :**
I think anidb tag on a folder do not work as intended for specials episods

**Context :** 

**My point is on [anidb-xxxx] tag folder**, NOT [anidb2-xxxx] nor [anidb3-xxxx] nor [anidb4-xxxx].
anidb do not rely on ScudLee list. `https://github.com/ScudLee/anime-lists`
So [anidb-xxxx] is just a single mapping of an anidb show without any tvdb content.

I try to organize Sword Art Online Alicization. I do not want that Alicization appears as season 3 like in tvdb. In ScudLee list, there is a mapping of Alicization to season 3, so i use [anidb-xxxx] tag which do not use  ScudLee list. Which is perfect for my need.

**The problem is :**

My Folders :
```

Sword Art Online\
          Sword Art Online \
                        Sword Art Online E01.mkv
                        Sword Art Online E02.mkv
                        ...
          Sword Art Online Alicization [anidb-13493] \
                        Sword Art Online Alicization E01.mkv
                        Sword Art Online Alicization E02.mkv
                        ...
                        Sword Art Online Alicization E24.mkv
                        Sword Art Online Alicization S00E01.mkv
```

In plex everything is ok. In Collection view I have 
```
Sword Art Online (the collection name)
             Sword Art Online (24 episodes with right titles, screenshots, abstract)
             Sword Art Online Alicization (2 seasons)
                             Season 1 : 24 episodes with titles and abstract from anidb)
                             Specials : 1 episode with titles/screenshot from TVDB and abstract from anidb <== The error
```

I should have title and abstract from anidb, this episode : https://anidb.net/episode/212503
**But I have abstract from anidb and title and screenshot from tvdb** (https://www.thetvdb.com/series/sword-art-online/episodes/4439303) ! 

Why is that ?

**Comment by ZeroQI** [comment]
Sword Art Online Alicization [anidb-13493] have 2 specials not mapped propertly:
- S00E01 'Recollection' is mapped to TheTVDB ID 259640 'Sword Art Online' s00e01 'Sword Art Offline 1' instead of s00e24 'Alicization 18.5: Recollection'
- S00E02 'Reflection' is mapped to TheTVDB ID 259640 'Sword Art Online' s00e02 'Sword Art Offline 2' instead of s00e25 'Alicization 24.5: Reflection'

ScudLee's AnimeList https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list-master.xml for AniDB "13493":
```
  <anime anidbid="13493" tvdbid="259640" defaulttvdbseason="3" episodeoffset="" tmdbid="" imdbid="">
    <name>Sword Art Online: Alicization</name>
  </anime>
```
It should however be specials 1 and 2 under AniDB mapped to special 24 and 25 under TheTVDB:
```
  <anime anidbid="13493" tvdbid="259640" defaulttvdbseason="3" episodeoffset="" tmdbid="" imdbid="">
    <name>Sword Art Online: Alicization</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-24;2-25;</mapping>
    </mapping-list>
  </anime>
```
I have raised the issue to AnimeLists [https://github.com/ScudLee/anime-lists/issues/300] but I would really have appreciated logs to give me the mappings, would have spared 30 minutes, but i do appreciate the links to AniDB, TheTVDB and description... 

You use AniDB numbering for this series, but HAMA cross-references AniDB to TheTVDB for Metadata in ALL cases, otherwise you wouldn't get a thumbnail for the episode (TheTVDB only) or episode title in many languages (TheTVDB 99%). Generally looking at the Agent setting tell you which metadata source provides for which field, regardless of AniDB or TheTVDB associated series.

**Comment by ZeroQI** [comment]
Fix has been added to AnimeLists
To do:
- delete Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\AnimeLists\anime-list-master.xml
-  custom match a series seasrching for the title "clear-cache" then cancel should pull latest version
- refresh metadata (might not change the first screenshot downloaded) so plex dance necessary

**Comment by StudioEtrange** [comment]
Oh  very very thank you!

> You use AniDB numbering for this series, but HAMA cross-references AniDB to TheTVDB for Metadata in ALL cases

Good to know, because it is not what I have understood in ASS readme. `Uses ScudLee mapping` is mentionned on anidb2 anidb3 anidb4, NOT on anidb.

Maybe a word on this in the readme ?

**Comment by ZeroQI** [comment]
Ass use it to remap season and episode number BUT metadata is an agent
issue and Scudlee's mapping is used consistently in HAMA so no need to
update ASS readme...

**Comment by StudioEtrange** [comment]
Thank your for your very quick answers !

But there is still a pb : 

What i have done :

* delete and refresh anime-list-master file
* done The Plex Dance®:
```
remove show/movie from library
rescan library files
empty trash
clean bundles
https://support.plex.tv/hc/en-us/articles/200392106-Library-Actions 126 <— scan library files, empty trash, clean bundles
bring names and structures into compliance/Move LMA/etc
replace corrected show/movie into library
rescan library files
```


And now the special episode S1 
* have the good abstract from anidb
* **wrong title** : "2019-02-17" instead of "Recollection"
* a screenshot I dont know from where, but **not the one from TVDB**

I have tried with filename `Sword Art Online Alicization S00E01.mkv` or `Sword Art Online Alicization S01.mkv`

**Comment by StudioEtrange** [comment]
My bad,
There is no problem anymore.

My previous post was about a Hama misconfiguration on title section.

Everything is good!
