### ISSUE TITLE
Logs - Specials without Absolute Numbers appearing in regular logs

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#363]
Hi @ZeroQI - it looks like when specials have a null value in the absolute number field on TheTVDB, when using TVDB4, they get committed to the "Missing Episodes" log versus the "Missing Specials" log still. See example below:

`TVDBid: 321285 | Title: 'Boruto: Naruto Next Generations' | Missing Episodes: ['0-0 (s0e1-3)', '127 (s1e127)', '129 (s1e129)']`

Logs: 
[Boruto Naruto Next Generations.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3778725/Boruto.Naruto.Next.Generations.zip)

**Comment by sven-7** [comment]
Ah crap - sorry about that! Nice you can transfer the issue.

**Comment by ZeroQI** [comment]
Present abs eps: {'130': '8', '24': '1', '25': '2', '26': '2', '27': '2', '20': '1', '21': '1', '22': '1', '23': '1', '28': '2', '29': '2', '4': '1', '8': '1', '119': '7', '120': '7', '121': '7', '122': '7', '123': '7', '124': '7', '125': '7', '126': '8', '128': '8', '118': '7', '59': '4', '58': '4', '55': '4', '54': '4', '57': '4', '56': '4', '51': '3', '50': '3', '53': '4', '52': '4', '115': '7', '114': '7', '88': '5', '89': '5', '111': '7', '110': '7', '113': '7', '112': '7', '82': '5', '83': '5', '80': '5', '81': '5', '86': '5', '87': '5', '84': '5', '85': '5', '3': '1', '7': '1', '108': '7', '109': '7', '102': '6', '103': '6', '100': '6', '101': '6', '106': '7', '107': '7', '104': '6', '105': '6', '39': '3', '38': '3', '33': '2', '32': '2', '31': '2', '30': '2', '37': '2', '36': '2', '35': '2', '34': '2', '60': '4', '61': '4', '62': '4', '63': '4', '64': '4', '65': '4', '66': '4', '67': '4', '68': '4', '69': '4', '2': '1', '6': '1', '99': '6', '98': '6', '91': '5', '90': '5', '93': '6', '92': '5', '95': '6', '94': '6', '97': '6', '96': '6', '11': '1', '10': '1', '13': '1', '12': '1', '15': '1', '14': '1', '17': '1', '16': '1', '19': '1', '18': '1', '117': '7', '116': '7', '48': '3', '49': '3', '46': '3', '47': '3', '44': '3', '45': '3', '42': '3', '43': '3', '40': '3', '41': '3', '1': '1', '5': '1', '9': '1', '77': '5', '76': '5', '75': '5', '74': '5', '73': '5', '72': '5', '71': '5', '70': '4', '79': '5', '78': '5'}
Missing: ['0-0 (s0e1-3)', '127 (s1e127)', '129 (s1e129)']

TheTVDBv2.py lines 160-171:
```
      ### Check for Missing Episodes ###
      is_missing = False
      if not(str(Dict(episode_json, 'airedSeason'))=='0' and str(Dict(episode_json, 'airedEpisodeNumber')) in list_sp_eps) and \
         not(metadata_source in ('tvdb3', 'tvdb4') and str(abs_number) in list_abs_eps) and \
         not(not movie and season in media.seasons and episode in media.seasons[season].episodes):
        is_missing = True
        Log.Info('[ ] {:>7} s{:0>2}e{:0>3} anidbid: {:>7} air_date: {}'.format(numbering, season, episode, anidbid, Dict(episode_json, 'firstAired')))
        air_date = Dict(episode_json, 'firstAired')
        air_date = int(air_date.replace('-','')) if air_date.replace('-','').isdigit() and int(air_date.replace('-','')) > 10000000 else 99999999
        if int(time.strftime("%Y%m%d")) <= air_date+1:  pass #Log.Info("TVDB - Episode '{}' missing but not aired/missing '{}'".format(numbering, air_date))
        elif season=='0':                               tvdb_special_missing.append(episode)
        elif metadata_source!='tvdb6':                  episode_missing_season.append( str(abs_number)+" ("+numbering+")" if metadata_source in ('tvdb3', 'tvdb4') else numbering)
```

TheTVDBv2.py lines 256-258:
```
    if metadata_source.startswith("tvdb") or metadata_source.startswith("anidb") and not movie and max(map(int, media.seasons.keys()))>1:
      if episode_missing:          error_log['Missing Episodes'         ].append("TVDBid: %s | Title: '%s' | Missing Episodes: %s"          % (common.WEB_LINK % (common.TVDB_SERIE_URL + TVDBid, TVDBid), Dict(TheTVDB_dict, 'title'), str(episode_missing        )))
      if tvdb_special_missing:     error_log['Missing Specials'         ].append("TVDBid: %s | Title: '%s' | Missing Specials: %s"          % (common.WEB_LINK % (common.TVDB_SERIE_URL + TVDBid, TVDBid), Dict(TheTVDB_dict, 'title'), str(tvdb_special_missing   )))
```

Need to find why tvdb4-321285 makes missing eps '127 (s1e127)', '129 (s1e129)' go in missing specials instead of missing eps.

**Comment by sven-7** [comment]
Those episodes were actually missing for me - so that should be accurate. I did that to validate the test.

**Comment by sven-7** [comment]
Here are the logs once I added them.  Just the specials showing up in the logs.

[Boruto Naruto Next Generations.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3790677/Boruto.Naruto.Next.Generations.agent-update.log)

**Comment by EndOfLine369** [comment]
Hey @ZeroQI, its all caused by the 's08e000' being set.

Issue line is here: https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/TheTVDBv2.py#L143
```python
if ms and usl:  season, episode = Dict(mappingList, 'absolute_map', str(abs_number), default=(ms if usl else str(int(ms)+1), None))[0], str(abs_number)
```
And caused by this update: https://github.com/ZeroQI/Hama.bundle/commit/e1852f1ec22890e76fa3bfc54b79f7148da10108
When `season!='0'` was removed from the if test.

So season 0 entries are getting set to a season if max_season+1 and episode of 0 as season 0.
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/TheTVDBv2.py#L135
```python
abs_number = Dict(episode_json, 'absoluteNumber', default=0 if season=='0' else abs_number+1)
```

**Comment by sven-7** [comment]
@EndOfLine369 - anything quick to change I can test or is this more substantial?

**Comment by ZeroQI** [comment]
@EndOfLine369 Coincidently, re-wrote for simplicity and to fix a bug the same code in bug https://github.com/ZeroQI/Hama.bundle/issues/366, as tvdb3 and 4 are following tvdb absolute numbering, and there is no ep number duplicatees so i can simplify the code greatly from
```
      ### ep translation
      anidbid=""
      abs_number = Dict(episode_json, 'absoluteNumber', default=0 if season=='0' else abs_number+1)
      if anidb_numbering:
        if Dict(mappingList, 'defaulttvdbseason_a'):  season, episode          = '1', str(abs_number)
        else:                                         season, episode, anidbid = anidb_ep(mappingList, season, episode)
      elif metadata_source=='tvdb3':  
        episode             = str(abs_number)
      elif metadata_source=='tvdb4':  
        ms, usl                         = Dict(mappingList, 'absolute_map', 'max_season'), Dict(mappingList, 'absolute_map', 'unknown_series_length')
        if ms and usl:  season, episode = Dict(mappingList, 'absolute_map', str(abs_number), default=(ms if usl else str(int(ms)+1), None))[0], str(abs_number)
        if season not in media.seasons or episode not in media.seasons[season].episodes:  #tvdb4 with custom season folder mapping
          for s in media.seasons:
            if str(abs_number) in media.seasons[s].episodes:  #if str(abs_number) in list_abs_eps
              season, episode = s, str(abs_number)
              break      
      elif metadata_source=='tvdb5':  
        episode, abs_number = str(Dict(episode_json, 'absoluteNumber') or abs_number), int(Dict(episode_json, 'absoluteNumber') or abs_number)
```
to:
```
      ### ep translation [Thetvdb absolute numbering followed, including in specials to stay accurate with scudlee's mapping]
      anidbid=""
      abs_number = Dict(episode_json, 'absoluteNumber', default=0 if season=='0' else abs_number+1)
      if anidb_numbering:
        if Dict(mappingList, 'defaulttvdbseason_a'):  season, episode          = '1', str(abs_number)
        else:                                         season, episode, anidbid = anidb_ep(mappingList, season, episode)
      elif metadata_source in ('tvdb3', 'tvdb4'):  
        if str(abs_number) in list_abs_eps:  #if abs id exists on disk, leave specials with no translation
          for s in media.seasons:
            if str(abs_number) in media.seasons[s].episodes:
              season, episode = s, str(abs_number)
              break
          else:  continue
      elif metadata_source=='tvdb5':  
        episode = str(abs_number)
```

Opinions?

**Comment by ZeroQI** [comment]
@sven-7 Can you please test if this resolves your issue?

**Comment by sven-7** [comment]
Yes - I’ll update the code and let you know.

**Comment by sven-7** [comment]
Confirming. Everything seems to be working as expected now! This should be good to commit.
