### ISSUE TITLE
find a different place for the X-Plex-Token

### ISSUE THREAD

**Issue by OttoKerner** [ZeroQI/Hama.bundle#42]
When supporting users in the Plex Forums, users are often asked to attach their zipped log folders to their error reports.

If they have the HAMA bundle installed, they are **publishing** their X-Plex-Token, which is a security nightmare and opens up the roads for rogue users accessing the servers.

Ususally, users are asked to clear out their log folders before gathering sets of log files, simply as a precaution to divulge only the necessary amount of information, pertaining to the diagnosis of malfunctions.
Here, it is also unfortunately that the X-Plex-Token is placed into the log folder. If a user is following this request from a supporting forum user, their HAMA install might be incapacitated afterwards.

I therefore ask you to find a different place to store the X-Plex-Token, to avoid the above issues.

**Comment by ZeroQI** [comment]
It is the scanner that allow as an option users to enter it manualy in that file so they have a log per library. It is not generated nor required.

Since both the scanner and agent run on multiple platforms, finding a common working folder path is impossible. 

I could use user folder but then nobody will find the logs and could crash on aome platforms...

Since this issue happen only when users willingly enter their key in that file, it is a user created issue.
