### ISSUE TITLE
Plug-in Support files zip

### ISSUE THREAD

**Issue by Hobblestoned** [ZeroQI/Hama.bundle#441]
In the Read ME file under installation it states there is an Pug in support zip or that it creates it been trying to trouble shoot and can't figure out why it isn't working

**Comment by ZeroQI** [comment]
Here is the readme location for the installation part [https://github.com/ZeroQI/Hama.bundle#Installation]:

> To install Hama, it's like other Plex agents: Get the latest source zip in https://github.com/ZeroQI/Hama.bundle > "Code" > "Download Zip". Inside the Hama.bundle-master.zip you will have the folder "Hama.bundle-master" to rename to "Hama.bundle" and place in Plex plugin folder [https://support.plex.tv/hc/en-us/articles/201106098-How-do-I-find-the-Plug-Ins-folder-] or Plex main folder / "Plug-ins"

Additionally, the troubleshooting section [https://github.com/ZeroQI/Hama.bundle#troubleshooting] show:

> [...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.system.log (show why the agent cannot launch)

If the agent doesn't start, this log file would show why, but you need the agent installed at the right location
- There used to be a zip of folders to decompress in the agent data folders, but that has long been deprecated when the way to create folders automatically was added, 

You do not state which source for your readme, no logs despite a list being given in troubleshooting section, we don't even known the OS or hardware platform, so i will close that incident report.

forums.plex.tv would be more suitable, so ANY user can assist you since they installed successfully, not just the main developers when there are 8 other bug reports a few month old which are not resolved to date
