### ISSUE TITLE
Support for multiple tmdbids or imdbids

### ISSUE THREAD

**Issue by reconman** [ZeroQI/Hama.bundle#442]
There are anime-lists entries with 2 comma-seperated IMDB or IMDB ids in case the anidb entry has 2 entries.

One example for that is:
```
  <anime anidbid="10583" tvdbid="267440" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="tt3646944,tt3646946">
    <name>Gekijouban Shingeki no Kyojin</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-14;2-15;</mapping>
    </mapping-list>
  </anime>
```

Another example with multiple tmdbids:
```
<anime anidbid="10977" tvdbid="275609" defaulttvdbseason="0" episodeoffset="" tmdbid="334361,357413" imdbid="">
    <name>Wake Up, Girls! Zoku Gekijouban</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-3;2-4;</mapping>
    </mapping-list>
  </anime>
```

Is my assumption right that Hama and ASS can't handle that at the moment?

**Comment by ZeroQI** [comment]
First example
- anidbid="10583" Gekijouban Shingeki no Kyojin https://anidb.net/anime/10583
- tvdbid="267440" Attack on Titan https://thetvdb.com/series/attack-on-titan
- imdbid="tt3646944" Attack on Titan: Crimson Bow and Arrow (2014) https://www.imdb.com/title/tt3646946/
- imdbid="tt3646946" Gekijôban Shingeki no Kyojin Kôhen: Jiyû no tsubasa (2015) https://www.imdb.com/title/tt3646946/

There is two movies in anidb s00e01-02, pointing to TheTVdB s00e14-15 and no way to pinpoint the IMDB entries to a specific episode (yes we could check the titles to try to map if meta is available but if AniDB and TheTVDB meta are there, what meta for eps will be missing???)

Second example
- anidbid="10977" Wake Up, Girls! Zoku Gekijouban https://anidb.net/anime/10977
- tvdbid="275609" Wake Up, Girls! https://www.thetvdb.com/series/wake-up-girls
- tmdbid="334361" Wake Up, Girls! Beyond the Bottom (2015) https://www.themoviedb.org/movie/334361-wake-up-girls
- tmdbid="357413" Wake Up, Girls! The Shadow of Youth (2015) https://www.themoviedb.org/movie/357413-wake-up-girls-zoku-movie-2

There is two movies in anidb s00e01-02, pointing to TheTVdB s00e03-04 and no way to pinpoint the TMDB entries to a specific episode (yes we could check the titles to try to map if meta is available but if AniDB and TheTVDB meta are there, what meta for eps will be missing???)

I don't see added value in these metadata source for series since it points to episode/movies we can't map to the episode number. One entry supported only.

I have added support for TMDB IDs (movies) with Hama, helping live movies support amongst other things.
