### ISSUE TITLE
TheTVDB to AniDB reverse mapping maps two episode to the same season and episode, resulting in bad metadata

### ISSUE THREAD

**Issue by littleneko** [ZeroQI/Hama.bundle#496]
The "Evangelion" movie "新世紀エヴァンゲリオン劇場版 Air / まごころを, 君に" (https://anidb.net/anime/202) and "新世紀エヴァンゲリオン劇場版 シト新生" (https://anidb.net/anime/326) display the episode as "Evangelion TV" (https://anidb.net/anime/326)

Same as the other anime movie and tv, like movie "冴えない彼女の育てかた Fine" (https://anidb.net/anime/13626) and TV "冴えない彼女の育てかた" (https://anidb.net/anime/10538).

The TV:
![image](https://user-images.githubusercontent.com/6368915/147390268-9ab48fbb-f9c6-4780-8bbe-b2d0b2d51837.png)

The Movie:
![image](https://user-images.githubusercontent.com/6368915/147390285-feeebd5a-d366-480f-a3d4-1fd8a8b496eb.png)
![image](https://user-images.githubusercontent.com/6368915/147390301-dcb6b95d-3838-412d-8fad-2d2c7015e899.png)

**Comment by ZeroQI** [comment]
No scanner logs
no agent search log
No agent update log
Which title and source is used is in the series specific update log at the end

**Comment by littleneko** [comment]
The scanner log and agent log:

[[Salender-Raws] Evangelion.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/7776636/Salender-Raws.Evangelion.filelist.log)
[[Salender-Raws] Evangelion.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/7776637/Salender-Raws.Evangelion.scanner.log)
[[Salender-Raws] Evangelion.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/7776634/Salender-Raws.Evangelion.agent-search.log)
[[Salender-Raws] Evangelion.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/7776635/Salender-Raws.Evangelion.agent-update.log)

**Comment by ZeroQI** [comment]
Technical analysis:

[Salender-Raws] Evangelion\Death & Rebirth\[Salender-Raws] Evangelion - Death & Rebirth (DVD 924x524 x264 AC3 5.1).mkv in filelist.log
Mapped to s01e01 in scanner.log
Assigned to anidb-326 in search.log so anidb numbering is used

metadata.seasons[ 1].episodes[  1]
[?] rank: 0, source_title: TheTVDB, title: "使徒、襲来"
[x] title                          Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB']'  Value: '使徒、襲来'

Showing in logs the title affectation for s01e01
Mapping show AniDB s01e01-02 maps to TVDB s00e01
```
 'TVDB': {'s0e0': ('0', '1', '326'), 's0e1': ('1', '1', '326'), 's-1': {'326': '0'}},
  'tvdbcount': 1}
```
TheTVDB detected the following episodes present:
[X]    s0e1 s01e001 anidbid:     326 air_date: 1997-03-15 abs_number: 0, title: 新世紀エヴァンゲリオン劇場版 シト新生
[X]    s1e1 s01e001 anidbid: xxxxxxx air_date: 1995-10-04 abs_number: 1, title: 使徒、襲来
 - [1] title:   [ja] 使徒、襲来

Because of TheTVDB file détection, two episodes are detected and assigned to s01e01, so the first mapping is lost... A failsafe and algorithm correction needs to be coded indeed.

https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/TheTVDBv2.py line 186

**Comment by ZeroQI** [comment]
The function that maps TheTVDB to AniDB ep number has flaws
- To be fixed. Bug located in this function: https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AnimeLists.py#L299
- failsafe to not allow multiple mappings to the same ep. Failsafe to be implimented after this function call: https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/TheTVDBv2.py#L171

**Comment by ZeroQI** [comment]
Your issue is that the mapping assign 2 tvdb eps to s01e-001, already mentioned on 
- https://github.com/ZeroQI/Hama.bundle/issues/490
- https://github.com/ZeroQI/Hama.bundle/issues/496
- https://github.com/ZeroQI/Hama.bundle/issues/500
- https://github.com/ZeroQI/Hama.bundle/issues/504

Will keep 500 which has better description and pinpointed the change that broke it, and close other bug reports
