### ISSUE TITLE
Episode summary only updates to correct language after next episode added

### ISSUE THREAD

**Issue by quashtaki** [ZeroQI/Hama.bundle#499]
Hello, I'm having trouble with the language of summaries of airing anime (specifically Attack on Titan and Demon Slayer atm, but it's happened before with My Hero Academia and other shows). The summary will be in Japanese, even though TheTVDB has the summary in English. Refreshing metadata does not solve the issue. When the next episode gets added however, the summary gets changed to the correct language. I've tried making a new library, but the issue still persists. Sorry if this is expected/intended behavior, can't find anything about it but it's very possible I'm just terrible at searching.

Hama config: [p1](https://i.imgur.com/R7nQ7G1.png), [p2](https://i.imgur.com/IsWLQoT.png)
What the episodes look like: [AoT](https://i.imgur.com/4Dx4Pvx.png), [Demon Slayer](https://i.imgur.com/cVXwTOt.png)
Logs (library name: Anime):

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/7917393/com.plexapp.agents.hama.log)
[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/7917394/com.plexapp.system.log)
[Attack on Titan (2013) [tvdb2-267440].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/7917392/Attack.on.Titan.2013.tvdb2-267440.scanner.log)
[Attack on Titan (2013) [tvdb2-267440].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/7917395/Attack.on.Titan.2013.tvdb2-267440.agent-search.log)
[Attack on Titan (2013) [tvdb2-267440].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/7917396/Attack.on.Titan.2013.tvdb2-267440.agent-update.log)
(not sure if I'm supposed to upload another log file).

**Comment by ZeroQI** [comment]
Summary are in the language of the library, English in this case and We cache the results so the important is the content of the cache file

This could be seen here:
common.LoadFile() - File cached locally - Filename: 'TheTVDB/json/267440/series_en.json', Age: '5.21 days', Limit: '6 days', url: 'https://api.thetvdb.com/series/267440?en'

5 hours after you copied the logs the tvdb Jason cache will be outdated and download a new copy

[=] originally_available_at        Sources: (AniDB),TheTVDB                                               Inside: '['TheTVDB', 'AniDB']'  Value: '2022-01-17'

It's only 5 days since the episode aired in Japan FFS!!!
When it happens, do a match search for series called 'clear-cache' then cancel it, then refresh your series metadata...
