### ISSUE TITLE
[QUESTION] is it possible to provide episodes unique id?

### ISSUE THREAD

**Issue by ArabCoders** [ZeroQI/Hama.bundle#510]
Hello,

The new plex agents provide unique id for each episode for example

```xml
<MediaContainer>
    <Video guid="plex://episode/5d9c0b767b5c2e001e678d76" type="episode" title="Departure">
        <Guid id="imdb://tt1640230"/>
        <Guid id="tmdb://883937"/>
        <Guid id="tvdb://1926031"/>
    </Video>
</MediaContainer>
```

i simplified the xml payload just to give an idea of how the new agents provide the external GUIDs, is it possible to for Hama to provide those ids as well?

**Comment by ArabCoders** [comment]
Hi 

Thank you for the response, those ids are usually used to sync the watch state using plugins and tools like trakt.tv etc, between different media servers like jellyfin and emby.

**Comment by ZeroQI** [comment]
This XML is internal to Plex
- If it had an agent accessible field like metadata.seasons[x].episodes[y].guid it would be possible, but that is not the case to my knowledge...
- If i edit XMLs and write them, it will lead to corruption since Plex also will do that concurrently, and agents are not meant to write Plex XMLs (i did load the library XML for providing unique functionality and writing agent based XML files and cash but not writing Plex own XML database files)...

In short, you want HAMA to synchronise read status but give the Plex propriatary XML as example, there is a logical leap there...

Wouldn't installing Trakt.tv scrobbler do that ? Could not figure out how Trakt.tv agent does it, way too complex
https://github.com/trakt/Plex-Trakt-Scrobbler/blob/master/Trakttv.bundle/Contents/Code/main.py

I do not know how to update safely this XML, and Third party Plex agents can't do so to my knowledge, so don't think it can be done. New Plex agents are in C++ cna may be able to do that...

**Comment by ArabCoders** [comment]
Thank you for your explanation, i have solved this problem in my own watchstate tool by using something i call relative unique id which is pretty much like plex GUIDs for now. im just wondering do you have list of possible dbs prefix hama uses?
for example i noticed right now the following

anidb-(showid), tvdb-(showid), tvdb2-(showid), tvdb3-(showid)

my tool is able to parse this one for now as i don't know how many variation hama uses for db identifiers. 
right now i am able to parse hama://(db:anidb)-(id:showid),

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/__init__.py#L105
Force IDs: anidb anidb2 tvdb tvdb2 tvdb3 tvdb4 tvdb5 tmdb tsdb imdb

**Comment by ArabCoders** [comment]
Thank you, I am gonna list some assumptions from what i understand  from the code 

* There are 4 backends supported: `anidb`, `tvdb`, `imdb` and `tmdb|tsmb` << both of those prefixes refer to `themoviedb`. 
* the `id` after the `(db)-` is the `series/movie id`, if so how do you distinguish if it's series or movie ? thetvdb kinda garbled their ids and movies and series have separate IDs which can overlap i myself fixed it by prefixing the tvdb id by the actual content type for example, `tvdb://show/(id)`, `tvdb://episode/(id)` and `tvdb://movie/(id)`

Sorry if im bothering you.

**Comment by ZeroQI** [comment]
Tmdb for movies, Tsdb for series, I thought it was clever and consistent...
I do not support thetvdb movies currently so no conflict...
