### ISSUE TITLE
Tvdb posters not getting  grabbed.

### ISSUE THREAD

**Issue by Eagle1337** [ZeroQI/Hama.bundle#512]
I have  my posters as:
AniList, AniDB, tvdb4, TheMovieDb, FanartTV and i have Load all poster metadata sources  checked but tvdb posters for shows don't get saved.

**Comment by ZeroQI** [comment]
No logs, they would show if the url is gathered as expected, and if so, could be Plex database corrupted or firewall/ad blocking software issue

**Comment by Eagle1337** [comment]
> No logs, they would show if the url is gathered as expected, and if so, could be Plex database corrupted or firewall/ad blocking software issue

It may be a database thing, but I can't overly go and restart the stupid thing now,
I know when i try to match things it willl only show either anidb results or tvdb results and not both.

**Comment by ZeroQI** [comment]
If you have single season it matches on Anidb only unless no result found
If you have season 2+ it matches on tvdb only
Working as designed
The matching had no bearing on poster source as long as both IDs are in the XML mapping file

**Comment by Eagle1337** [comment]
Load all poster metadata sources  I presume only does the main series poster then?

**Comment by ZeroQI** [comment]
Are you saying that the main TheTVDB poster gets saved? You can see the output I included and how it lists all posters? Therefore it give them to Plex...

**Comment by Eagle1337** [comment]
[https://i.imgur.com/20sHBcc.png](https://i.imgur.com/20sHBcc.png)
I grabbed the 2 posters from tvdb and uploaded them myself, it only grabbed the one.

**Comment by ZeroQI** [comment]
That's season poster, not what I would call 'tvdb posters for shows'...

**Comment by Eagle1337** [comment]
[https://thetvdb.com/series/toradora/seasons/official/1]https://thetvdb.com/series/toradora/seasons/official/1l)
there's 4 posters there, with hama have only grabbing one of them.

**Comment by ZeroQI** [comment]
Since series posters are OK and one poster is grapped for season posters:
- Title "Tvdb posters not getting grabbed." is false 
- "tvdb posters for shows don't get saved." is false 
- "Load all poster metadata sources I presume only does the main series poster then?" is false

Proper problem statement was:
- [My toradora](https://pastebin.com/j4XihNVy)
- Only one TheTVDB season poster captured when thetvdb web page show multiple []https://thetvdb.com/series/toradora/seasons/official/1l
- Logs show only one season poster found in summary logs at the end
`[x] posters                  ( 1)  Sources: AniList, AniDB, tvdb4, TheMovieDb, (TheTVDB), FanartTV        Inside: '[]'  Value: '{u'https://thetvdb.plexapp.com/banners/seasons/83277-1.jpg': (u'TheTVDB\\seasons\\83277-1.jpg', 67, u'https://thetvdb.plexapp.com/banners/seasons/83277-1_t.jpg')}'
`

TheTVDB section about posters does show season poster specifically
`common.LoadFile() - File cached locally - Filename: 'TheTVDB\json\83277\images_season_en.json', Age: '5.59 days', Limit: '6 days', url: 'https://api.thetvdb.com/series/83277/images/query?keyType=season'`

This point to TVDB file https://api.thetvdb.com/series/83277/images/query?keyType=season
https://api.thetvdb.com/series/83277/images/query?keyType=season

```
{"data":[
  {"id":61810348,"keyType":"season","subKey":"0","fileName":"seasons/83277-0-2.jpg","languageId":0,"language":"en","resolution":"680x1000","ratingsInfo":{"average":0,"count":0},"thumbnail":"seasons/83277-0-2_t.jpg","seriesLastUpdated":1647215842},
  {"id":61810350,"keyType":"season","subKey":"1","fileName":"seasons/83277-1.jpg","languageId":0,"language":"en","resolution":"680x1000","ratingsInfo":{"average":0,"count":0},"thumbnail":"seasons/83277-1_t.jpg","seriesLastUpdated":1647215842}
]}
```

Thetvdb api show only one season poster per season, so working as designed, \You could technically complain to TheTVDB, but they will say we have to migrate to TheTVD v4 and v2 API will be stopped and the whole agent will stop working any day now to be honest and TheTVDB v4 require subscriptions, and i morally oppose to them getting money for my labour and i don't have the will anymore to code a massive upgrae for something i don't even use for myself and haven't been for 4 years now...
