### ISSUE TITLE
Need Help: Movie Naming Not Working / Collections made containing "Show" item

### ISSUE THREAD

**Issue by DudeShift** [ZeroQI/Hama.bundle#534]
Note: I am new to Plex and trying to use Hama and ASS to organize my Anime library since I like the idea of movies relating to a Anime series can be in the same Plex library. However I am running into some issues. 

### Naming Movies Not Working:
For example, lets take the series "Cowboy Bebop" which has 26 episodes and one movie.

At first I tried using the tvdb formatting so:
```
Anime/
  Cowboy Bebop/
    Cowboy Bebop - S00E03 - Cowboy Bebop The Movie - Complete Movie.mkv
    Cowboy Bebop - S01E01 - Asteroid Blues.mkv
    ...
```
However that made a collection which said Cowboy Bebop had two seasons (Specials and Season 1). And when going into Specials the movie was listed as Episode 3 Cowboy Bebop The Movie. I personally didn't like how it was formatted as I saw other auto created "collections" having shows (which I will get into later in my 2nd issue...). Also testing watching the series, tvdb for the movie has "Special Position Airs before season 1, episode 23" which didn't work. I prefer to watch the movie at the end of the series anyways but I want to figure this out for actual specials like OVAs or "basically extended episode" movies at are inbetween series / "Seasons".

So then I tried using anidb and forcing the movie:
```
Anime/
  Cowboy Bebop/
    Cowboy Bebop The Movie - Complete Movie [anidb-219] .mkv
    Cowboy Bebop - 01 - Asteroid Blues.mkv
    ...
```
However that just made the movie not appear in Plex. It was listed under the first episode of the series when clicking "Get Info" in plex. I later found it by changing my library view to "Folder", and it had all the metadata of the first episode of the series (Name, Picture, Description). So I tried also forcing the series:
```
Anime/
  Cowboy Bebop/
    Cowboy Bebop [anidb-23]/
      Cowboy Bebop - 01 - Asteroid Blues.mkv
       ...{other episodes}...
    Cowboy Bebop The Movie [anidb-219]/
      Cowboy Bebop The Movie - Complete Movie [anidb-219].mkv
    
```
And again it is still being added under the first episode when clicking "Get Info" However now when changing library view to "Folder", Plex says there are no items in Cowboy Bebop The Movie [anidb-219]. I have tried added "- 1" in the movie file or removing the "- Complete Movie" tag as stated in the [ASS readme](https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/README.md#one-libray-for-both-movies-and-tv-series). 

### Ghost in the Shell Stand Alone Complex - Solid State Society (2007) Test
To test with another Anime (for sanity check):
```
Anime/
  Ghost in the Shell Stand Alone Complex/
    Season 1/
      Ghost in the Shell Stand Alone Complex - S01E01 - Section-9.mkv
      ...{other episodes}...
    Solid State Society (2007)/
      Ghost in the Shell Stand Alone Complex - Solid State Society (2007) - Complete Movie.mkv
```
Also when re-scanning the library, the "Solid State Society" movie is not found in the Plex libarary (nor in Folder view) but is listed under "Get Info" of the first episode in Season 1. I have not testing with OVAs since I want to fix Movies first before tackling trying to get those working.

---
### Collections made that only have the show (one item)
So after a library scan some of the Anime series will have a collection made that have a single item inside that is listed as the Anime "Show". It seems to happen more with tvdb formatting so `/Anime/{SeriesName}/{Season 1}/...` but I have had it happen with a Anime "Show"s with one season folder to three seasons + specials folder. 

I don't understand why these collections are being made that the only item is the show. I can understand if its meant to be able to link movies in a separate Anime Movie Plex Library (since you can have one collection span multiple Plex Libraries) to link say the Neon Genesis Evangelion TV Series to the rebuild movies since they are theatrical movies. 

I also suspect that the collections might be made to have the Anime "Show" and relative movies that are in the folder of the series. 

However: I have multiple Anime series that are formatted in tvdb but only some have a auto-made collection for just the show, and some that have this collections have no other movies, ovas.  

Band-Aid fix is to delete the collections since I would prefer not to have to click into a collection, then click into the "show" before being able to select a season. Its one extra click but it shouldn't be there in the first place?

---
Again, I am new to any sort of database naming and trying my best to follow the Hama / ASS guides since I would like to have movies that are basically extended episodes within the same Plex library. 

It would be amazing if someone could share with me a file structure for Ghost in the Shell Stand Alone Complex since that has two series (Seasons), OVAs, Movies, and theatrical movies (which for theatrical I am okay with having in a separate Plex Library), so that I can learn to base other Anime series off of.

**Comment by DudeShift** [comment]
After some more testing, it seems like you have to delete a "show" to reset the metadata. The problem with doing this is when trying to delete in Plex, it wants to delete the show from the filesystem (the actual files). So a workaround is deleting the whole library. 

I have tried setting up a testing library (type TV Shows just as I was doing above) so I can reset the metadata for a show. 

What "worked" was putting a movie in its own folder with the exact same name, then wait 2 minutes still the option to fix match appears to rename it / get metadata. For example `/Cowboy Bebop The Movie (2002)/Cowboy Bebop The Movie (2002).mkv`.

The movie though is listed as its own show, having its own season 1, and the first episode being the movie. I understand that I could hide season numbers, add episode to a collection with the Anime series. Having it listed a episode isn't a huge deal breaker but was hoping for a more seamless experience so I don't have to look up a watch order for specials that are in between "seasons". 

_Also this time it has auto-made two collections that are the same for Ghost in the Shell Stand Alone Complex (collection with a single item, the "show")._ 

---
I wish (probably like other before me) there was a way to manual make entries within Plex since it would have been faster then spending the last two days researching how to get this working. 

My next plan is just to make two Anime libraries, one for Movies and one for "TV Shows", link the related Anime movies via collections, and try to hide non-theatrical (basically extended episodes) from the library so I can sort by theatrical Anime movies. 

I would rather do that then for a movie to be listed as a "Season" and a "episode". I understand if this is a limitation of Plex using the TV Show library setting to hack in away to have Anime. 

No idea what to do for OVAs / Specials since for Ghost in the Shell Stand Alone Complex, since I have them in their own Specials folder for each season `/Season 2/Specials/` but they get put into one main Specials folder in the "Show" item in Plex while still saying that the Anime has a extra season (since its counting the specials as a season).

---

Anime on Plex is a mess. If anyone can share a screen shot of what the file structure and how it should look like in Plex that would be very helpful since I have to refer back to a database (anidb, MAL, Anilist, etc) to get a watch order then that defeats the purpose of using Plex.

**Comment by ZeroQI** [comment]
Movie libraries are for Movies and Series libraries are for episodes.
- I made the agent able to see movies as episodes as a workaround in both scanner and agent. You number the movie as s00e03 and it end up there, so whatMovie libraries are for Movies and Series libraries are for episodes.
- I made the agent able to see movies as episodes as a workaround in both scanner and agent. You number the movie as s00e03 and it end up there, so what is the issue? 
- if you want the right viewing order for specials before/after normal episode order, that is a Plex issue, which doesn't support it while XBMC does...

You cannot renumber files/folders without changing folder file content, Plex will know the files didn't change and metadata won't change. Google "Pled Dance"... 

Collection are single strings assigned to the series or movie in their respective libraries. The agent cannot know if another one use it.
- You have to go to agent settings to change collection source if they bug you. 'Local' metadata source there will create a season for grouping folders, so you have control. Q
- You have library option to hide items in collections so they don't show twice, and can hide single seasons to spare a click. 

You have a use case scenario, Plex forum for the scanner since it is responsible for the individual entry season and ep number would have been a better choice for this type of queries since it is not a metadata issue but a numbering one... 

I did made some tvdb5 mode for chronological order but the episode will be a mess afterwards as no longer the original order and will not account some movies... You expect the viewing order to be seamless and that just isn't a Plex thing, even less a third party agent responsabilité, at best a scanner issue as it décidé season and épisode number for TV libraries...  is the issue? 
- if you want the right viewing order for specials before/after normal episode order, that is a Plex issue, which doesn't support it while XBMC does...

You cannot renumber files/folders without changing folder file content, Plex will know the files didn't change and metadata won't change. Google "Pled Dance"... 

Collection are single strings assigned to the series or movie in their respective libraries. The agent cannot know if another one use it.
- You have to go to agent settings to change collection source if they bug you. 'Local' metadata source there will create a season for grouping folders, so you have control. Q
- You have library option to hide items in collections so they don't show twice, and can hide single seasons to spare a click. 

You have a use case scenario, Plex forum for the scanner since it is responsible for the individual entry season and ep number would have been a better choice for this type of queries since it is not a metadata issue but a numbering one... 

I did made some tvdb5 mode for chronological order but the episode will be a mess afterwards as no longer the original order and will not account some movies... You expect the viewing order to be seamless and that just isn't a Plex thing, even less a third party agent responsabilité, at best a scanner issue as it décidé season and épisode number for TV libraries...

**Comment by ZeroQI** [comment]
https://www.reddit.com/r/PleX/comments/gh39w8/this_is_why_you_should_use_asshama_for_anime_and/

**Comment by DudeShift** [comment]
Thank you @ZeroQI for your reply.

> I made the agent able to see movies as episodes as a workaround in both scanner and agent. 

From looking at HAMA documentation I can not find this stated but after trying to use the scanner & agent it makes sense why movies are listed as a episode in Plex. 

> You number the movie as s00e03 and it end up there, so what is the issue?

Personally, I find the idea of having a movie being listed in Plex as a third episode. I understand now its a limitation of Plex. I also don't like having a "Show" being listed in Plex having one more "Season" then it should. Since Plex counts the Specials as another Season. 

For example with Cowboy Bebop using Western formatting, it is a series with one season and a movie. I would prefer for Plex to not state that it is two seasons. 

> Google "Plex Dance"

Thank you for informing me about this, that makes sense. 

> agent settings to change collection source if they bug you

Thank you for explaining this, I will look through the databases and find a metadata source that I like. I will probably end up creating collections myself within Plex since the "local" folder groupings aren't working for me. When having a Season and a Movie folder in the same main Anime folder, two collections are made: The "Show" with seasons and a collection for the movie that is listed as its own season. I am going to assume its the limitation with Plex. 

> You have library option to hide items in collections so they don't show twice, and can hide single seasons to spare a click

That does work when you delete the auto-made collections. The auto-made collections will have a single item in it, the "Show", even when the "Show" only has one "Season". 

> https://www.reddit.com/r/PleX/comments/gh39w8/this_is_why_you_should_use_asshama_for_anime_and/

Thank you for an example of what the library looks like in Plex.

---

I am going to close the issue since it seems like I what thought Plex, ASS, and HAMA were are not what they and other say it is. Yes they pull metadata but due to Plex limitations they can not give accurate season numbering. I understand this is not the fault of ASS or HAMA but the fault is with Plex built for Western media having to use a "Plex TV Show' library format. It is nice that you can create a movie as a episode to force it into the "TV Show" library format but I do not wish for a movie to be listed a like episode 3 of its own season. 

I hope one day Plex or a similar service can allow for this. Thank you very much again for your help.

**Comment by ZeroQI** [comment]
Some do not like tvdb format for specials indeed, and use a movie as it's
own series while using the setting to remove single season folders, grouped
in a collection. There are ways to use fake seasons to group things in
anidb relationship order but I personally find it messy...

**Comment by ZeroQI** [comment]
@dudeshift There is no metadata based player that can allow movies and series in the same libraries, period, being Plex, Emby, and on other platforms, the metadata agent is tvdb Or AniDB or TMDB, not a mix like i did, exception being Kodi anidb.net agent i reuse the anime'list xml format from and it since has been forked since the original was no longer maintained. This level of customisation is appreciated by many. you can always use colletions and separate movies and series in separate libraries

You can have movies show up as s01e01 of their own series using ANiDB numbering, and using the option to hide seasons for single season series you will have very little perceivable differences. closing this ticket
