### ISSUE TITLE
Movies broken into "episodes" with AniDB

### ISSUE THREAD

**Issue by JathTyki** [ZeroQI/Hama.bundle#566]
Hello,

Using this agent, it seems impossible to scan for a movie on AniDB that is utilizing multiple parts or episodes.

In this example, I'm using the Code Geass three movies, or https://anidb.net/anime/12567. It's classified as a Movie, so HamaTV doesn't recognize it of course as a TV show. However when scanning with the HamaMovies agent, it won't properly detect the movie. If manually matching, you can only match a single part to the entry, which of course leaves two others as orphans.

Thank you.

**Comment by ZeroQI** [comment]
The agent doesn't scan, the scanner does however... It is literally the first line in the scanner readme that explain the scanner is responsible for the season and episode number. The agent does metadata... 

Classified as a movie, really? Why does it have 3 episodes then, you know, in the 'EP' volumn, 'EP' being short for episodes...

If you created a Movie library, using a movie agent and wondering why it cannot detect what is a 3 part series (since there are three EPISODE numbers) , then you lack the cognitive abilities to understand the inticaties, and need to trust me on the fact you need a series library to dump movies and series inside, the scanner and agent will manage as long as you have proper filenames. 

That is a use case and should have been asked in plex forum or attach series specific scanner and agent logs, path in each readme...

**Comment by JathTyki** [comment]
Dude, wasn't trying to spout shade or something at you, I apologize if I came across that way. I also apologize for not seeing that first line.

However, the reason I mentioned it as a movie was because of AniDB literally saying movie. While I understand I see the, you know, "EP" part, the type of it on the website literally says Movie, as shown in this lovely little piece I screen shotted for you: https://imgur.com/pZVSOCo

Again, wasn't trying to cause any sh*t for you or anything. Just was wondering what was up. I'll take another look on my end to see why it may not be detected properly, and won't bother you again dude.

Have a good one.

**Comment by ZeroQI** [comment]
They are movies realistically you are correct, but from Plex and hama perspective they do not care about the length, and are a single TV series and all would work with a series library

If you have a movie library like it seems you do, you cannot have an episode number assigned by the Plex movie scanner (i did not provide a movie scanner so that's on Plex) , therefore you cannot make it work as you want. 

**Create a Series library pointing to the same root folder, hide seasons for single seasons and hide items in collections, that should do the trick**

I am a but harsh beccause you included no logs and no folder no filename, and i did describe in which cases to create Bug reports or plex forums and logs location, and seem to be a plex movie scanner / plex limitation issue and created on wrong project.. . Also if you looked at closed bug reports, most people attach logs on first post... 

That should be a use case question on plex forum, with a new thread to keep the support alive as they close after 3 month inactivity, thetvdb changes means this might stop working fully as soon as they force new paid api usage, and i lost the drive, and write this on my phone and it is frustating to do on a phone, even more so with all information missing to do a proper reply...

**Comment by JathTyki** [comment]
Understood, and again, I apologize. Should've been more diligent in my post.

I've always loved the HamaTV agent and it is sad to potentially see it go.

Hope you have a good day / night man.

**Comment by ZeroQI** [comment]
The sadest is, while i have Plex on my Synology nas, hardly ever use it so difficult to keep implicated, will probably fix if it breaks but if thetvdb force monetization, will be difficult to fix but they should have migrated couple years back so hopefully stays as is...

**Comment by JathTyki** [comment]
Hopefully there is a little solace in that your work doesn't go unnoticed. I have used this agent for the better part of 6+ years at this point, and is the first thing I do if I ever need to redo Plex for whatever reason.

Thank you for your hard work.

**Comment by ZeroQI** [comment]
Thank you. Plex is the only ecosystem where you can modify the series scanner to accept movies to have anime movies and series in a single series library...
