### ISSUE TITLE
Working but names all season ep's the same thing

### ISSUE THREAD

**Issue by cyris69** [ZeroQI/Hama.bundle#79]
For instance, Dragon Ball, found this agent because TVDB was bad for this. However, it found the background, banner, poster, description season covers everything perfectly. However season 2-5 all episodes match those of the first. How can I correct that?

Main series area
https://imgur.com/a/q9b2s

Side by side Season 1 and Season 2
https://imgur.com/a/bj7Ly

**Comment by ZeroQI** [comment]
I need to see the custom scanner log and the agent log, as i need to see if tvdb/2/3/4 mode from the scanner was used, or if an anidbid is used as main id for that serie, but something is definitely off.
The agent log need to show dragon ball serie so i know which id is used and re-check the behaviour

**Comment by ZeroQI** [comment]
try https://raw.githubusercontent.com/ZeroQI/Hama.bundle/b24679173e7f7548863092e501a9648e2c76c56c/Contents/Code/__init__.py and see if it fixes, and if specials and everything works in all your series, as i don't know if i broke anyhting

**Comment by ZeroQI** [comment]
Please try again with code on the pull request above, once confimed it works, will push it to the master code

**Comment by ZeroQI** [comment]
Please update me with the outcome on latest code

**Comment by lordfiSh** [comment]
I just encountered the same Problem, but after renaming the Filename to a [Plex Standard](https://support.plex.tv/hc/en-us/categories/200028098-Media-Preparation) it worked perfectly with your Scanner

**Comment by ZeroQI** [comment]
@lordfiSh do you happen to still have the filenames before renaming ? maybe in scanner logs... Would like to see if i can modify the scanner to support it...

**Comment by lordfiSh** [comment]
@ZeroQI 
> [FB] Black Lagoon [S01] [E01] (BD 1080p 10Bit x264 DTS).mkv

**Comment by ZeroQI** [comment]
Thanks for that.

Brackets are useful for info to be kept in filenames but scrapped by the scanner processing, ironically like the only things not in brackets there: BD 1080p 10Bit x264 DTS

You could use "s01e01", "s01 e01", "1x01", "101"(don't like that one) but [S01] [E01] not really.

We could however add to SERIES_RX a regex string matching this format (escape the brackets '\[')
  '^(?P<show>.*?) \[(?P<season>[0-9]{1,2})\] \[(?P<ep>[0-9]{1,3})\] (?P<title>.*)$'

Have added support in the scanner for it, please test original filenames, should work back
However, since it search for ep number in filename scraping brackets first, might have bad numbering at times if numbers words (without letter) are present...
