### ISSUE TITLE
Posters & Backgrounds not loading!

### ISSUE THREAD

**Issue by JLChamberlain** [ZeroQI/Hama.bundle#85]
The System matches the metadata perfectly but it never loads the posters and backgrounds for the series. I haven't changed anything and did it exactly as suposed to. The images below show what I mean:

![screenshot 27](https://cloud.githubusercontent.com/assets/22307144/19412758/930415a0-9314-11e6-9261-26640e0d741b.png)
![screenshot 25](https://cloud.githubusercontent.com/assets/22307144/19412760/93073d98-9314-11e6-842b-ce028514ef16.png)
![screenshot 26](https://cloud.githubusercontent.com/assets/22307144/19412759/930710de-9314-11e6-8b35-e48daeaa624c.png)

**Comment by KingJ** [comment]
Have you created the Agent's data folder? All of the posters, backgrounds etc are stored here, but this folder can't be created automatically. Take a look at the [Installation](https://github.com/ZeroQI/Hama.bundle#installation) section, specifically the bits that refer to the "Plug-Ins Support" folder/Agent data folder.

**Comment by JLChamberlain** [comment]
Thanks for your help!, that fixed it!. I just downloaded the Plug-Ins Support from the Installation section and replaced the folder. What I dont understand is why isn't this is the main download?

**Comment by KingJ** [comment]
Great, glad to hear that worked! 😄 
@ZeroQI would probably be the best person to comment as to why this isn't in the main download, but at a guess i'd say it's because the main plugin and the agent data folders need to go into completely different directories.

**Comment by JLChamberlain** [comment]
Thats understandable!, that should of been the first thing that was written on the ReadMe file and people wouldn't have to go through with this

**Comment by ZeroQI** [comment]
Github source need to be the root of agent folders... since the readme list the folders and the release tab has it it doesn't cause issues to most people...

I could remove the folders but recreating libraries would take forever...

You did not follow the install section since you didn't put the folders. You didn't follow troubleshooting section that states what to do with missing posters, nor attaching the logs asked to be attached for troubleshooting issues....

I don't think the readme was therefore incomplete. Feel free to edit it if you think or feel it can be made clearer and i will accept the changes
