### ISSUE TITLE
Directors and Writers not showing up

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#89]
I noticed with a lot of series that I was not seeing the Director or Writer, despite having put them into TVDB myself.  Here is an example from Ajin.  Unsure if any other content isn't getting put through either, but the director and writer are in the metadata being downloaded.

![screen shot 2016-11-20 at 2 58 33 am](https://cloud.githubusercontent.com/assets/18091557/20461481/a2954668-aecd-11e6-8e18-9ced92f18590.png)
![screen shot 2016-11-20 at 2 58 40 am](https://cloud.githubusercontent.com/assets/18091557/20461482/a298cb30-aecd-11e6-9a50-e25f0146829a.png)
![screen shot 2016-11-20 at 2 58 48 am](https://cloud.githubusercontent.com/assets/18091557/20461483/a29f746c-aecd-11e6-887e-6f85d8b557bc.png)
![screen shot 2016-11-20 at 3 00 16 am](https://cloud.githubusercontent.com/assets/18091557/20461484/a2a13c5c-aecd-11e6-8505-4d1a3a17abb2.png)

**Comment by ZeroQI** [comment]
modified my local copy to output strings

```
Log( "Plex role: " + str(plex_role) )
            for role in plex_role:
              for person in plex_role[role]:
                if role=="writers"   and person not in episodeObj.writers:   episodeObj.writers.add  (person);  Log("Writer:   '%s' added" % person)
                if role=="producers" and person not in episodeObj.producers: episodeObj.producers.add(person);  Log("Producer: '%s' added" % person)
                if role=="directors" and person not in episodeObj.directors: episodeObj.directors.add(person);  Log("Director: '%s' added" % person)
```
            
This outputs the following, confirming it is a plex issue, not updating producer director writers for episodes

```
2016-11-20 14:12:43,769 - com.plexapp.agents.hama (-b7ee4c0) : INFO (__init__/Update:674) - Plex role: {'producers': ['Oonogi Hiroshi'], 'directors': ['Kodama Kenji'], 'writers': ['Tanabe Yellow']}
2016-11-20 14:12:43,770 - com.plexapp.agents.hama (-b7ee4c0) : INFO (__init__/Update:674) - Producer: 'Oonogi Hiroshi' added
2016-11-20 14:12:43,770 - com.plexapp.agents.hama (-b7ee4c0) : INFO (__init__/Update:674) - Director: 'Kodama Kenji' added
2016-11-20 14:12:43,771 - com.plexapp.agents.hama (-b7ee4c0) : INFO (__init__/Update:674) - Writer:   'Tanabe Yellow' added

```

**Comment by sven-7** [comment]
Okay - I'll report it and post back here if I hear anything.

**Comment by KingJ** [comment]
It looks like Plex has indeed changed how directors and writers are added - see [this forum thread](https://forums.plex.tv/discussion/222804/plugin-framework-has-changed-and-there-is-no-documentation) for discussion around it and the [OMDB metadata agent code](https://github.com/piplongrun/OpenMovieDatabase.bundle/blob/master/Contents/Code/__init__.py#L110) as an example of the 'new' way of handling it.

I'm going to have a go at updating Hama to use the new format.

**Comment by sven-7** [comment]
Even with the latest update, I'm still not seeing writers or directors showing up for shows I have listed in AniDB or TVDB modes.

**Comment by KingJ** [comment]
Could you share your com.plexapp.agents.hama.log file? You should see a line in there that starts with "AniDB Creator data:" followed by the director/writer data. 

For one of the shows that isn't showing any director/writer data could you also please go to any episode, click the triple dots on the left, click Info and then click View XML. On the page that opens, copy the XML and paste it here.

**Comment by KingJ** [comment]
Ok, i've confirmed this issue locally. The root 'cause' is that Hama [only adds director and writer metadata to movies](https://github.com/ZeroQI/Hama.bundle/blob/fc264beced5cbe102870920b9401e19eafdff5fe/Contents/Code/__init__.py#L519), but Plex does support adding it to shows. This was the case before my recent commit, but I had approached it from the view of fixing it to support Plex's new director/writer metadata storage method rather than realising that your actual issue was that Hama didn't add director/writer metadata to shows via _any_ method - working or otherwise!

_However_, how Plex stores directors and writers differs from how it stores actors, which complicates things slightly. Actors are stored at the show level, whereas directors and writers are stored at the episode level. The problem is though that AniDB stores director and writer metadata at the show level, and doesn't break it down per-episode like TheTVDB does. Directors and writers can and do change from episode to episode so i'd say TheTVDB is more 'correct' in this aspect.

@ZeroQI: To fix this, i'm proposing getting the director/writer metadata from AniDB for movies only, as happens today, but for shows grab the per-episode data from TheTVDB instead. Any objections?

**Comment by ZeroQI** [comment]
It's logical so no objection
