### ISSUE TITLE
External subtitles not working. 

### ISSUE THREAD

**Issue by dzfacts** [ZeroQI/Hama.bundle#91]
When anime is in normal folder as personal media, plex reads the subtitles.
When I use HamaTV to get metadata from anime, subtitles are not found.
No update or refresh is solving the problem.
When I use a different agent all subtitles load normally.

**Comment by ZeroQI** [comment]
Agent related. Name of file and format of subtitle would help (ssa, srt, or embedded in mkv, mp4) since i need to reproduce the issue

**Comment by dzfacts** [comment]
Thanks for your help Zero, I think I cant make a clear scenario to help you to reproduce the issue.
So, I'm working with the following files (media and subtitles) -> [http://pastebin.com/cBvL0Uah](http://pastebin.com/cBvL0Uah)
Just for test, using the absolute series scanner with the TVDB agent I got all the subtitles working, as you can see on the right side of this printscreen -> [https://snag.gy/LUlpoj.jpg](https://snag.gy/LUlpoj.jpg)
While using absolute series scanner + Hama agent all the external metadata (episode names and description) works great but no subtitles is found (window on the left).

**Comment by dzfacts** [comment]
This issue is happening on freenas too but I'm using plex for windows on the print.

**Comment by ZeroQI** [comment]
An example of your naming:
- ONE PIECE\[HDTV]_ONE_PIECE_324_(1280x720_WMV9)_[2142BE4F].avi
- ONE PIECE\ONE_PIECE_324_(1280x720_WMV9)_[2142BE4F].pob.pt.ass

So the only difference is the agent then. TheTVDB code doesn't give me any hints though:
https://github.com/plexinc-agents/TheTVDB.bundle/blob/master/Contents/Code/__init__.py

The page https://support.plex.tv/hc/en-us/articles/200471133-Adding-Local-Subtitles-to-Your-Media indicate the naming doesn't match convention, should be called:
[HDTV]_ONE_PIECE_324_(1280x720_WMV9)_[2142BE4F].Portuguese.ass

Could you try supported naming convention? If still fails, it means it is caused by the agent but it doens't do anything with local subtitles so i am puzzled

**Comment by dzfacts** [comment]
The "Local Media Assets (TV)" option did the trick without any name change, thanks.
But that's really awkward it's not checked by default, I mean, I've used the plugin before, but never had to change anything, just use it out of the box.
Do you still need to check if the conventions you mentioned can solve it? I dont think it would because plex can match the subtitles by the ISO-639-1 (2-letter) which I'm already using.

**Comment by ZeroQI** [comment]
Updated https://github.com/ZeroQI/Hama.bundle/blob/master/README.md
no that's grand, thanks for the update
